package com.pgcrm.service;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.pgcrm.config.SystemConfigProperties;
import com.pgcrm.entity.Bed;
import com.pgcrm.entity.Block;
import com.pgcrm.entity.Building;
import com.pgcrm.entity.BuildingConfig;
import com.pgcrm.entity.Floor;
import com.pgcrm.entity.Room;
import com.pgcrm.entity.enums.BedStatus;
import com.pgcrm.entity.enums.EbSplitMethod;
import com.pgcrm.repository.BedRepository;
import com.pgcrm.repository.BlockRepository;
import com.pgcrm.repository.BuildingConfigRepository;
import com.pgcrm.repository.BuildingRepository;
import com.pgcrm.repository.FloorRepository;
import com.pgcrm.repository.RoomRepository;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.RequiredArgsConstructor;
import lombok.Setter;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.math.BigDecimal;
import java.time.LocalTime;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;

/**
 * Service responsible for the full lifecycle management of building layouts —
 * creation, retrieval, and update — via the Owner UI.
 *
 * <p>Handles the complete spatial entity hierarchy persisted atomically within each operation:</p>
 * <pre>
 *   Building → Floor → [Block] → Room → Bed
 * </pre>
 *
 * <p>Buildings may contain a mix of block-organised and standalone (no-block) rooms on
 * the same floor, allowing flexible layout modelling:</p>
 * <ul>
 *   <li><strong>Block-organised:</strong> Rooms are grouped under named blocks (e.g., "Block A").</li>
 *   <li><strong>Standalone:</strong> Rooms are directly attached to a floor with no intermediate block.</li>
 * </ul>
 *
 * <p><strong>Room Numbering:</strong></p>
 * <ul>
 *   <li>If the request provides explicit room numbers via {@link RoomConfig#getRoomNumbers()},
 *       those are used verbatim.</li>
 *   <li>Otherwise, room numbers are auto-generated:
 *       standalone rooms use {@code <floorPrefix>-<index>} (e.g., {@code G-01});
 *       block rooms use {@code <floor><blockCode>-<sharing>S[<index>]} (e.g., {@code 1A-2S3}).</li>
 * </ul>
 *
 * <p><strong>Bed Labelling:</strong> Bed labels are auto-generated by appending a sequential
 * integer suffix to the room prefix (e.g., {@code G011}, {@code G012} for a 2-sharing ground floor room).</p>
 *
 * <p><strong>Update Safety:</strong> The {@link #updateBuilding} method refuses to delete any
 * room that contains at least one occupied bed, throwing an {@link IllegalArgumentException}
 * to prevent data loss during active stays.</p>
 *
 * @see BuildingSetupRequest
 * @see BuildingEditRequest
 * @see BuildingCreationResult
 */
@Service
@RequiredArgsConstructor
@Slf4j
public class BuildingSetupService {

    private final BuildingRepository        buildingRepository;
    private final FloorRepository           floorRepository;
    private final BlockRepository           blockRepository;
    private final RoomRepository            roomRepository;
    private final BedRepository             bedRepository;
    private final BuildingConfigRepository  buildingConfigRepository;
    private final SystemConfigProperties    systemConfig;

    // ── Request DTO (Creation) ────────────────────────────────────────────────

    /**
     * Request payload for creating a new building from the Owner UI.
     *
     * <p>Contains the building's metadata, configuration overrides, and the complete
     * floor/block/room spatial hierarchy to create in a single transaction.</p>
     */
    @Getter @Setter @NoArgsConstructor
    public static class BuildingSetupRequest {
        /** The building's display name. Must be unique (case-insensitive). */
        @JsonProperty("name")
        private String name;

        /** The building's physical address. */
        @JsonProperty("address")
        private String address;

        /** Whether food cost is bundled into the room rent (overrides YAML default). */
        @JsonProperty("foodIncludedInRent")
        private Boolean foodIncludedInRent;

        /** Whether guests may cancel meal opt-ins after the cutoff time (overrides YAML default). */
        @JsonProperty("allowMealCancellations")
        private Boolean allowMealCancellations;

        /** Per-building breakfast price override; falls back to YAML default if null. */
        @JsonProperty("breakfastPrice")
        private BigDecimal breakfastPrice;

        /** Per-building lunch price override; falls back to YAML default if null. */
        @JsonProperty("lunchPrice")
        private BigDecimal lunchPrice;

        /** Per-building dinner price override; falls back to YAML default if null. */
        @JsonProperty("dinnerPrice")
        private BigDecimal dinnerPrice;

        /** Per-building omelette add-on price override; falls back to YAML default if null. */
        @JsonProperty("omelettePrice")
        private BigDecimal omelettePrice;

        /** Per-building boiled-egg add-on price override; falls back to YAML default if null. */
        @JsonProperty("boiledEggPrice")
        private BigDecimal boiledEggPrice;

        /** Whether the building config allows Omelette add-on. */
        @JsonProperty("offerOmelette")
        private Boolean offerOmelette;

        /** Whether the building config allows Boiled Egg add-on. */
        @JsonProperty("offerBoiledEgg")
        private Boolean offerBoiledEgg;

        /** Per-building washing machine usage price override; falls back to YAML default if null. */
        @JsonProperty("washingMachinePrice")
        private BigDecimal washingMachinePrice;

        /** The EB split method for this building (e.g., {@code "EQUAL_SPLIT"}, {@code "METER_BASED"}). */
        @JsonProperty("ebSplitMethod")
        private String ebSplitMethod;

        /** The time after which breakfast and lunch selections are locked for the next day. */
        @JsonProperty("breakfastCutoffTime")
        private LocalTime breakfastCutoffTime;

        /** The time after which dinner selections are locked for the current day. */
        @JsonProperty("dinnerCutoffTime")
        private LocalTime dinnerCutoffTime;

        /**
         * Whether the breakfast/lunch cutoff applies on the previous calendar day
         * ({@code true}) or on the target date itself ({@code false}).
         */
        @JsonProperty("isPreviousDay")
        private Boolean isPreviousDay;

        /** The floor-level layout hierarchy to create. */
        @JsonProperty("floors")
        private List<FloorSetup> floors = new ArrayList<>();
    }

    /**
     * Describes a single floor within a {@link BuildingSetupRequest}.
     */
    @Getter @Setter @NoArgsConstructor
    public static class FloorSetup {
        /** The floor number: {@code 0} = Ground, {@code 1} = First, etc. */
        private int              number;

        /** The human-readable floor label (e.g., {@code "Ground Floor"}, {@code "1st Floor"}). */
        private String           label;

        /** Standalone rooms on this floor (not grouped into a block). */
        private List<RoomConfig> rooms  = new ArrayList<>();

        /** Block-organised room groups on this floor. */
        private List<BlockSetup> blocks = new ArrayList<>();
    }

    /**
     * Describes a named block of rooms within a {@link FloorSetup}.
     */
    @Getter @Setter @NoArgsConstructor
    public static class BlockSetup {
        /** The block's display name (e.g., {@code "Block A"}). */
        private String           name;

        /** The room configurations contained in this block. */
        private List<RoomConfig> roomConfigs = new ArrayList<>();
    }

    /**
     * Describes a batch of rooms with the same sharing type and base rent.
     *
     * <p>A single {@link RoomConfig} can represent multiple rooms (specified by {@link #count}).
     * Explicit room numbers may be provided via {@link #roomNumbers}; otherwise they
     * are auto-generated.</p>
     */
    @Getter @Setter @NoArgsConstructor
    public static class BedConfig {
        @JsonProperty("bedLabel")
        private String bedLabel;
    }

    @Getter @Setter @NoArgsConstructor
    public static class RoomConfig {
        /**
         * The sharing type (number of beds) for rooms of this configuration.
         * Typically {@code 1}, {@code 2}, {@code 3}, or {@code 4}.
         */
        private int              sharing;

        /** The number of rooms to create with this configuration. */
        private int              count;

        /** The monthly base rent for rooms of this configuration. */
        private BigDecimal       baseRent;

        /** Whether the rooms in this configuration are AC. */
        @JsonProperty("isAc")
        private boolean          isAc;

        /**
         * Optional explicit room numbers for each room in this batch.
         * Must have exactly {@link #count} entries if provided; any missing or blank
         * entries trigger auto-generation for that position.
         */
        private List<String>     roomNumbers = new ArrayList<>();
        private List<BedConfig>  beds = new ArrayList<>();
    }

    /**
     * Summary response returned after a successful building creation or update.
     */
    @Getter @Setter
    public static class BuildingCreationResult {
        /** The UUID of the created or updated building. */
        private String buildingId;

        /** The display name of the created or updated building. */
        private String buildingName;

        /** The total number of floors in the building. */
        private int totalFloors;

        /** The total number of blocks across all floors. */
        private int totalBlocks;

        /** The total number of rooms across all floors and blocks. */
        private int totalRooms;

        /** The total number of beds across all rooms. */
        private int totalBeds;
    }

    // ── Edit DTOs ─────────────────────────────────────────────────────────────

    /**
     * Request payload for updating an existing building's layout and configuration
     * from the Owner UI.
     *
     * <p>Existing entities (floors, blocks, rooms) are identified by their {@code id} field.
     * Entities without an {@code id} are created as new. Entities present in the database
     * but absent from this payload are deleted (with occupied-bed safety check).</p>
     */
    @Getter @Setter @NoArgsConstructor
    public static class BuildingEditRequest {
        private String          name;
        private String          address;
        private Boolean         foodIncludedInRent;
        private Boolean         allowMealCancellations;
        private BigDecimal      breakfastPrice;
        private BigDecimal      lunchPrice;
        private BigDecimal      dinnerPrice;
        private BigDecimal      omelettePrice;
        private BigDecimal      boiledEggPrice;
        private Boolean         offerOmelette;
        private Boolean         offerBoiledEgg;
        private BigDecimal      washingMachinePrice;
        private String          ebSplitMethod;
        private LocalTime       breakfastCutoffTime;
        private LocalTime       dinnerCutoffTime;
        private Boolean         isPreviousDay;
        private List<FloorEdit> floors = new ArrayList<>();
    }

    /** Edit descriptor for a single floor. */
    @Getter @Setter @NoArgsConstructor
    public static class FloorEdit {
        /** The existing floor UUID, or {@code null} / blank to create a new floor. */
        private String          id;
        private int             number;
        private String          label;
        private List<BlockEdit> blocks = new ArrayList<>();
        private List<RoomEdit>  rooms  = new ArrayList<>();
    }

    /** Edit descriptor for a single block. */
    @Getter @Setter @NoArgsConstructor
    public static class BlockEdit {
        /** The existing block UUID, or {@code null} / blank to create a new block. */
        private String         id;
        private String         name;
        private List<RoomEdit> rooms = new ArrayList<>();
    }

    /** Edit descriptor for a single room. */
    @Getter @Setter @NoArgsConstructor
    public static class RoomEdit {
        /** The existing room UUID, or {@code null} / blank to create a new room. */
        private String     id;
        private String     roomNumber;
        private int        sharing;
        private BigDecimal baseRent;
        @JsonProperty("isAc")
        private boolean    isAc;
        /** The number of occupied beds in this room (read-only display field; not processed on write). */
        private int        occupiedBedsCount;
    }

    // ── Core Creation Logic ───────────────────────────────────────────────────

    /**
     * Creates a new building with its complete spatial hierarchy from the given request payload.
     *
     * <p>The entire creation — building, building config, floors, blocks, rooms, and beds —
     * is wrapped in a single {@link Transactional} boundary. If any step fails, the entire
     * hierarchy is rolled back.</p>
     *
     * <p><strong>Config Defaults:</strong> Any price fields not supplied in the request default
     * to the corresponding YAML global values from {@link SystemConfigProperties}. Cutoff times
     * default to {@code 22:00} (breakfast) and {@code 14:00} (dinner) if not provided.</p>
     *
     * @param req the fully populated {@link BuildingSetupRequest}.
     * @return a {@link BuildingCreationResult} summarising the created entities.
     * @throws IllegalArgumentException if the building name is blank or already exists.
     */
    @Transactional
    public BuildingCreationResult createBuilding(final BuildingSetupRequest req) {
        if (req.getName() == null || req.getName().isBlank()) {
            throw new IllegalArgumentException("Building name is required");
        }
        if (buildingRepository.findByNameIgnoreCase(req.getName()).isPresent()) {
            throw new IllegalArgumentException("A building with that name already exists");
        }

        final Building building = buildingRepository.save(
                Building.builder()
                        .name(req.getName().trim())
                        .address(req.getAddress() != null ? req.getAddress().trim() : "")
                        .build());
        log.info("✅ Owner created building: {}", building.getName());

        // Resolve EB split method — request > YAML default > hardcoded fallback.
        EbSplitMethod splitMethod = EbSplitMethod.EQUAL_SPLIT;
        try {
            if (req.getEbSplitMethod() != null) {
                splitMethod = EbSplitMethod.valueOf(req.getEbSplitMethod());
            } else if (systemConfig.getRules().getEbSplitMethod() != null) {
                splitMethod = EbSplitMethod.valueOf(systemConfig.getRules().getEbSplitMethod());
            }
        } catch (Exception ignored) {
            // Invalid enum value — silently fall back to EQUAL_SPLIT.
        }

        buildingConfigRepository.save(BuildingConfig.builder()
                .building(building)
                .foodIncludedInRent(req.getFoodIncludedInRent() != null ? req.getFoodIncludedInRent() : false)
                .allowMealCancellations(req.getAllowMealCancellations() != null ? req.getAllowMealCancellations() : true)
                .breakfastPrice(req.getBreakfastPrice()       != null ? req.getBreakfastPrice()       : systemConfig.getPricing().getBreakfast())
                .lunchPrice(req.getLunchPrice()               != null ? req.getLunchPrice()           : systemConfig.getPricing().getLunch())
                .dinnerPrice(req.getDinnerPrice()             != null ? req.getDinnerPrice()           : systemConfig.getPricing().getDinner())
                .omelettePrice(req.getOmelettePrice()         != null ? req.getOmelettePrice()         : BigDecimal.ZERO)
                .boiledEggPrice(req.getBoiledEggPrice()       != null ? req.getBoiledEggPrice()       : BigDecimal.ZERO)
                .washingMachinePrice(req.getWashingMachinePrice() != null ? req.getWashingMachinePrice() : BigDecimal.ZERO)
                .ebSplitMethod(splitMethod)
                .breakfastCutoffTime(req.getBreakfastCutoffTime() != null ? req.getBreakfastCutoffTime() : LocalTime.of(22, 0))
                .dinnerCutoffTime(req.getDinnerCutoffTime()       != null ? req.getDinnerCutoffTime()     : LocalTime.of(14, 0))
                .isPreviousDay(req.getIsPreviousDay() != null ? req.getIsPreviousDay() : true)
                .offerOmelette(req.getOfferOmelette() != null ? req.getOfferOmelette() : true)
                .offerBoiledEgg(req.getOfferBoiledEgg() != null ? req.getOfferBoiledEgg() : true)
                .build());

        int totalBlocks = 0, totalRooms = 0, totalBeds = 0;

        for (final FloorSetup fSetup : req.getFloors()) {
            final String floorLabel = fSetup.getLabel() != null ? fSetup.getLabel()
                    : (fSetup.getNumber() == 0 ? "Ground Floor" : fSetup.getNumber() + " Floor");

            final Floor floor = floorRepository.save(Floor.builder()
                    .building(building)
                    .floorNumber(fSetup.getNumber())
                    .floorLabel(floorLabel)
                    .build());

            // ── Standalone rooms on this floor ────────────────────────────────
            if (fSetup.getRooms() != null) {
                int rIdx = 1;
                for (final RoomConfig rc : fSetup.getRooms()) {
                    for (int i = 0; i < rc.getCount(); i++) {
                        final String roomNum = resolveRoomNumber(rc, i,
                                fSetup.getNumber() == 0 ? "G" : String.valueOf(fSetup.getNumber()), rIdx);
                        final Room room = roomRepository.save(Room.builder()
                                .floor(floor).block(null)
                                .roomNumber(roomNum)
                                .sharingType(rc.getSharing())
                                .baseRent(rc.getBaseRent())
                                .isAc(rc.isAc())
                                .build());

                        createBeds(room, rc.getSharing(), null, rc.getBeds());
                        totalRooms++;
                        totalBeds += rc.getSharing();
                        rIdx++;
                    }
                }
            }

            // ── Block-organised rooms on this floor ───────────────────────────
            if (fSetup.getBlocks() != null) {
                for (final BlockSetup bSetup : fSetup.getBlocks()) {
                    final Block block = blockRepository.save(
                            Block.builder().floor(floor).name(bSetup.getName()).build());
                    totalBlocks++;

                    // Extract the single-char block code from the name (e.g., "A" from "Block A").
                    String blockCode = bSetup.getName();
                    if (blockCode.contains(" ")) {
                        blockCode = blockCode.substring(blockCode.lastIndexOf(" ") + 1);
                    }

                    if (bSetup.getRoomConfigs() != null) {
                        for (final RoomConfig rc : bSetup.getRoomConfigs()) {
                            for (int r = 1; r <= rc.getCount(); r++) {
                                final String roomNum = hasExplicitRoomNumber(rc, r - 1)
                                        ? rc.getRoomNumbers().get(r - 1).trim()
                                        : fSetup.getNumber() + blockCode + "-" + rc.getSharing() + "S" + (rc.getCount() > 1 ? r : "");

                                final Room room = roomRepository.save(Room.builder()
                                        .floor(floor).block(block)
                                        .roomNumber(roomNum)
                                        .sharingType(rc.getSharing())
                                        .baseRent(rc.getBaseRent())
                                        .isAc(rc.isAc())
                                        .build());

                                createBeds(room, rc.getSharing(), blockCode, rc.getBeds());
                                totalRooms++;
                                totalBeds += rc.getSharing();
                            }
                        }
                    }
                }
            }
        }

        final BuildingCreationResult result = new BuildingCreationResult();
        result.setBuildingId(building.getId());
        result.setBuildingName(building.getName());
        result.setTotalFloors(req.getFloors().size());
        result.setTotalBlocks(totalBlocks);
        result.setTotalRooms(totalRooms);
        result.setTotalBeds(totalBeds);
        log.info("✅ Building '{}' created: {} floors, {} blocks, {} rooms, {} beds",
                building.getName(), result.getTotalFloors(), totalBlocks, totalRooms, totalBeds);
        return result;
    }

    /**
     * Retrieves the current layout and configuration of a building, structured for
     * round-trip editing in the Owner UI.
     *
     * <p>Floors are sorted in ascending floor-number order. Within each floor, block rooms
     * and standalone rooms are returned in separate lists to reflect the two-tier organisation.</p>
     *
     * @param buildingId the UUID of the {@link Building} to retrieve.
     * @return a {@link BuildingEditRequest} populated with the current state of the building.
     * @throws IllegalArgumentException if no building exists for the given ID.
     */
    public BuildingEditRequest getBuildingLayout(final String buildingId) {
        final Building building = buildingRepository.findById(buildingId)
                .orElseThrow(() -> new IllegalArgumentException("Building not found"));

        final BuildingEditRequest req = new BuildingEditRequest();
        req.setName(building.getName());
        req.setAddress(building.getAddress());

        final BuildingConfig config = buildingConfigRepository.findById(buildingId).orElse(null);
        if (config != null) {
            req.setFoodIncludedInRent(config.isFoodIncludedInRent());
            req.setAllowMealCancellations(config.isAllowMealCancellations());
            req.setBreakfastPrice(config.getBreakfastPrice());
            req.setLunchPrice(config.getLunchPrice());
            req.setDinnerPrice(config.getDinnerPrice());
            req.setOmelettePrice(config.getOmelettePrice());
            req.setBoiledEggPrice(config.getBoiledEggPrice());
            req.setOfferOmelette(config.isOfferOmelette());
            req.setOfferBoiledEgg(config.isOfferBoiledEgg());
            req.setWashingMachinePrice(config.getWashingMachinePrice());
            req.setEbSplitMethod(config.getEbSplitMethod() != null ? config.getEbSplitMethod().name() : null);
            req.setBreakfastCutoffTime(config.getBreakfastCutoffTime());
            req.setDinnerCutoffTime(config.getDinnerCutoffTime());
            req.setIsPreviousDay(config.isPreviousDay());
        }

        final List<Floor> floors = floorRepository.findByBuildingId(buildingId);
        floors.sort(Comparator.comparingInt(Floor::getFloorNumber));

        for (final Floor f : floors) {
            final FloorEdit fe = new FloorEdit();
            fe.setId(f.getId());
            fe.setNumber(f.getFloorNumber());
            fe.setLabel(f.getFloorLabel());

            // Block rooms
            for (final Block bl : blockRepository.findByFloorId(f.getId())) {
                final BlockEdit be = new BlockEdit();
                be.setId(bl.getId());
                be.setName(bl.getName());
                for (final Room r : roomRepository.findByBlockId(bl.getId())) {
                    be.getRooms().add(buildRoomEdit(r));
                }
                fe.getBlocks().add(be);
            }

            // Standalone rooms (no block)
            roomRepository.findByFloorId(f.getId()).stream()
                    .filter(r -> r.getBlock() == null)
                    .map(this::buildRoomEdit)
                    .forEach(re -> fe.getRooms().add(re));

            req.getFloors().add(fe);
        }
        return req;
    }

    /**
     * Updates an existing building's metadata, configuration, and spatial layout.
     *
     * <p>The update operation uses an "active ID set" strategy:</p>
     * <ol>
     *   <li>Floors, blocks, and rooms with an existing {@code id} are updated in-place.</li>
     *   <li>Entities without an {@code id} (or with a blank one) are created as new.</li>
     *   <li>After processing, all database entities whose IDs are <em>not</em> in the active
     *       set are deleted — floors, blocks, and rooms in that order.</li>
     * </ol>
     *
     * <p>Room sharing type changes trigger {@link #adjustRoomBeds} to add or remove
     * vacant beds accordingly, respecting the occupied-bed constraint.</p>
     *
     * @param buildingId the UUID of the building to update.
     * @param req        the edit request with the desired target state.
     * @return a {@link BuildingCreationResult} reflecting the counts after the update.
     * @throws IllegalArgumentException if the building name is blank, a name collision is detected,
     *                                  or a room deletion is blocked by occupied beds.
     */
    @Transactional
    public BuildingCreationResult updateBuilding(final String buildingId, final BuildingEditRequest req) {
        Building building = buildingRepository.findById(buildingId)
                .orElseThrow(() -> new IllegalArgumentException("Building not found"));

        if (req.getName() == null || req.getName().isBlank()) {
            throw new IllegalArgumentException("Building name is required");
        }
        if (!building.getName().equalsIgnoreCase(req.getName().trim())) {
            if (buildingRepository.findByNameIgnoreCase(req.getName().trim()).isPresent()) {
                throw new IllegalArgumentException("A building with that name already exists");
            }
        }
        building.setName(req.getName().trim());
        building.setAddress(req.getAddress() != null ? req.getAddress().trim() : "");
        buildingRepository.save(building);

        // Update BuildingConfig — only overwrite fields supplied in the request.
        final Building finalBuilding = building;
        BuildingConfig config = buildingConfigRepository.findById(buildingId)
                .orElseGet(() -> BuildingConfig.builder().building(finalBuilding).build());

        if (req.getFoodIncludedInRent()    != null) config.setFoodIncludedInRent(req.getFoodIncludedInRent());
        if (req.getAllowMealCancellations() != null) config.setAllowMealCancellations(req.getAllowMealCancellations());
        if (req.getBreakfastPrice()        != null) config.setBreakfastPrice(req.getBreakfastPrice());
        if (req.getLunchPrice()            != null) config.setLunchPrice(req.getLunchPrice());
        if (req.getDinnerPrice()           != null) config.setDinnerPrice(req.getDinnerPrice());
        if (req.getOmelettePrice()         != null) config.setOmelettePrice(req.getOmelettePrice());
        if (req.getBoiledEggPrice()        != null) config.setBoiledEggPrice(req.getBoiledEggPrice());
        if (req.getOfferOmelette()         != null) config.setOfferOmelette(req.getOfferOmelette());
        if (req.getOfferBoiledEgg()        != null) config.setOfferBoiledEgg(req.getOfferBoiledEgg());
        if (req.getWashingMachinePrice()   != null) config.setWashingMachinePrice(req.getWashingMachinePrice());
        if (req.getBreakfastCutoffTime()   != null) config.setBreakfastCutoffTime(req.getBreakfastCutoffTime());
        if (req.getDinnerCutoffTime()      != null) config.setDinnerCutoffTime(req.getDinnerCutoffTime());
        if (req.getIsPreviousDay()         != null) config.setPreviousDay(req.getIsPreviousDay());
        if (req.getEbSplitMethod() != null) {
            try {
                config.setEbSplitMethod(EbSplitMethod.valueOf(req.getEbSplitMethod()));
            } catch (Exception ignored) {
                // Invalid enum value — leave existing setting unchanged.
            }
        }
        buildingConfigRepository.save(config);

        // Active ID sets — used after processing to delete removed entities.
        final List<String> activeFloorIds = new ArrayList<>();
        final List<String> activeBlockIds = new ArrayList<>();
        final List<String> activeRoomIds  = new ArrayList<>();
        int totalBlocks = 0, totalRooms = 0, totalBeds = 0;

        for (final FloorEdit fe : req.getFloors()) {
            final Floor floor = upsertFloor(fe, building, activeFloorIds);

            // Standalone rooms on this floor
            if (fe.getRooms() != null) {
                for (final RoomEdit re : fe.getRooms()) {
                    final Room room = upsertRoom(re, floor, null, activeRoomIds);
                    totalRooms++;
                    totalBeds += re.getSharing();
                }
            }

            // Blocks and their rooms on this floor
            if (fe.getBlocks() != null) {
                for (final BlockEdit be : fe.getBlocks()) {
                    final Block block = upsertBlock(be, floor, activeBlockIds);
                    totalBlocks++;

                    if (be.getRooms() != null) {
                        for (final RoomEdit re : be.getRooms()) {
                            upsertRoom(re, floor, block, activeRoomIds);
                            totalRooms++;
                            totalBeds += re.getSharing();
                        }
                    }
                }
            }
        }

        // ── Clean up removed rooms ────────────────────────────────────────────
        for (final Room r : roomRepository.findByFloor_Building_Id(buildingId)) {
            if (!activeRoomIds.contains(r.getId())) {
                final List<Bed> beds     = bedRepository.findByRoomId(r.getId());
                final boolean   occupied = beds.stream().anyMatch(bed -> bed.getStatus() == BedStatus.OCCUPIED);
                if (occupied) {
                    throw new IllegalArgumentException(
                            "Cannot delete room " + r.getRoomNumber() + " because it contains occupied beds.");
                }
                bedRepository.deleteAll(beds);
                roomRepository.delete(r);
            }
        }

        // ── Clean up removed blocks ───────────────────────────────────────────
        for (final Block b : blockRepository.findByFloor_Building_Id(buildingId)) {
            if (!activeBlockIds.contains(b.getId())) {
                blockRepository.delete(b);
            }
        }

        // ── Clean up removed floors ───────────────────────────────────────────
        for (final Floor f : floorRepository.findByBuildingId(buildingId)) {
            if (!activeFloorIds.contains(f.getId())) {
                floorRepository.delete(f);
            }
        }

        final BuildingCreationResult result = new BuildingCreationResult();
        result.setBuildingId(building.getId());
        result.setBuildingName(building.getName());
        result.setTotalFloors(activeFloorIds.size());
        result.setTotalBlocks(totalBlocks);
        result.setTotalRooms(totalRooms);
        result.setTotalBeds(totalBeds);
        return result;
    }

    // ── Private Helpers ───────────────────────────────────────────────────────

    /**
     * Creates the specified number of beds for a room using sequential label suffixes.
     *
     * @param room   the parent {@link Room}.
     * @param count  the number of beds to create ({@link RoomConfig#getSharing()}).
     * @param prefix the label prefix appended with an integer index (e.g., {@code "G01"} → {@code "G011"}).
     */
    private void createBeds(final Room room, final int count, final String blockCode, final List<BedConfig> bedConfigs) {
        for (int i = 1; i <= count; i++) {
            String bedSuffix = "B" + i;
            if (bedConfigs != null && bedConfigs.size() >= i && bedConfigs.get(i - 1) != null && bedConfigs.get(i - 1).getBedLabel() != null) {
                bedSuffix = bedConfigs.get(i - 1).getBedLabel().trim();
            }

            String bedLabel;
            if (blockCode != null && !blockCode.isBlank()) {
                bedLabel = blockCode + "-" + room.getRoomNumber() + "-" + bedSuffix;
            } else {
                bedLabel = room.getRoomNumber() + "-" + bedSuffix;
            }

            bedRepository.save(Bed.builder()
                    .room(room)
                    .bedLabel(bedLabel)
                    .status(BedStatus.VACANT)
                    .build());
        }
    }

    /**
     * Adjusts the number of beds in a room to match a new sharing type.
     *
     * <p>If beds need to be added, they are created as {@link BedStatus#VACANT}.
     * If beds need to be removed, only {@link BedStatus#VACANT} beds are removed;
     * occupied beds block the reduction and cause an {@link IllegalArgumentException}.</p>
     *
     * @param room       the {@link Room} whose bed count is being adjusted.
     * @param newSharing the target number of beds.
     * @throws IllegalArgumentException if the reduction would require removing occupied beds.
     */
    private void adjustRoomBeds(final Room room, final int newSharing) {
        final List<Bed> beds         = bedRepository.findByRoomId(room.getId());
        final int       currentCount = beds.size();
        if (currentCount == newSharing) return;

        if (newSharing > currentCount) {
            final int diff = newSharing - currentCount;
            for (int i = 1; i <= diff; i++) {
                bedRepository.save(Bed.builder()
                        .room(room)
                        .bedLabel("R-" + room.getRoomNumber() + "-B" + (currentCount + i))
                        .status(BedStatus.VACANT)
                        .build());
            }
        } else {
            final long occupiedCount = beds.stream().filter(b -> b.getStatus() == BedStatus.OCCUPIED).count();
            if (occupiedCount > newSharing) {
                throw new IllegalArgumentException(
                        "Cannot reduce room " + room.getRoomNumber() + " to " + newSharing
                        + " sharing because it has " + occupiedCount + " occupied beds.");
            }

            int removed = 0;
            final int diff = currentCount - newSharing;
            for (final Bed b : beds) {
                if (removed >= diff) break;
                if (b.getStatus() == BedStatus.VACANT) {
                    bedRepository.delete(b);
                    removed++;
                }
            }
            if (removed < diff) {
                throw new IllegalArgumentException(
                        "Cannot reduce room " + room.getRoomNumber() + " sharing: insufficient vacant beds to remove.");
            }
        }
    }

    /**
     * Builds a {@link RoomEdit} DTO from a {@link Room} entity for the layout retrieval response.
     *
     * @param r the source {@link Room} entity.
     * @return a populated {@link RoomEdit}.
     */
    private RoomEdit buildRoomEdit(final Room r) {
        final RoomEdit re = new RoomEdit();
        re.setId(r.getId());
        re.setRoomNumber(r.getRoomNumber());
        re.setSharing(r.getSharingType());
        re.setBaseRent(r.getBaseRent());
        re.setAc(r.isAc());
        final List<Bed> beds     = bedRepository.findByRoomId(r.getId());
        final long      occupied = beds.stream().filter(bed -> bed.getStatus() == BedStatus.OCCUPIED).count();
        re.setOccupiedBedsCount((int) occupied);
        return re;
    }

    /**
     * Upserts a floor during the update flow — updates if an ID is present, creates otherwise.
     *
     * @param fe           the {@link FloorEdit} from the request.
     * @param building     the parent {@link Building}.
     * @param activeFloorIds the mutable list to register the floor's ID into.
     * @return the saved {@link Floor} entity.
     */
    private Floor upsertFloor(final FloorEdit fe, final Building building, final List<String> activeFloorIds) {
        final Floor floor;
        if (fe.getId() != null && !fe.getId().isBlank()) {
            final Floor existing = floorRepository.findById(fe.getId())
                    .orElseThrow(() -> new IllegalArgumentException("Floor not found: " + fe.getId()));
            existing.setFloorNumber(fe.getNumber());
            existing.setFloorLabel(fe.getLabel());
            floor = floorRepository.save(existing);
        } else {
            floor = floorRepository.save(Floor.builder()
                    .building(building)
                    .floorNumber(fe.getNumber())
                    .floorLabel(fe.getLabel())
                    .build());
        }
        activeFloorIds.add(floor.getId());
        return floor;
    }

    /**
     * Upserts a block during the update flow — updates if an ID is present, creates otherwise.
     *
     * @param be            the {@link BlockEdit} from the request.
     * @param floor         the parent {@link Floor}.
     * @param activeBlockIds the mutable list to register the block's ID into.
     * @return the saved {@link Block} entity.
     */
    private Block upsertBlock(final BlockEdit be, final Floor floor, final List<String> activeBlockIds) {
        final Block block;
        if (be.getId() != null && !be.getId().isBlank()) {
            final Block existing = blockRepository.findById(be.getId())
                    .orElseThrow(() -> new IllegalArgumentException("Block not found: " + be.getId()));
            existing.setName(be.getName());
            block = blockRepository.save(existing);
        } else {
            block = blockRepository.save(Block.builder().floor(floor).name(be.getName()).build());
        }
        activeBlockIds.add(block.getId());
        return block;
    }

    /**
     * Upserts a room during the update flow — updates if an ID is present, creates otherwise.
     * Adjusts beds via {@link #adjustRoomBeds} if the sharing type changes.
     *
     * @param re           the {@link RoomEdit} from the request.
     * @param floor        the parent {@link Floor}.
     * @param block        the parent {@link Block}, or {@code null} for standalone rooms.
     * @param activeRoomIds the mutable list to register the room's ID into.
     * @return the saved {@link Room} entity.
     */
    private Room upsertRoom(final RoomEdit re, final Floor floor, final Block block,
                             final List<String> activeRoomIds) {
        final Room room;
        if (re.getId() != null && !re.getId().isBlank()) {
            final Room existing = roomRepository.findById(re.getId())
                    .orElseThrow(() -> new IllegalArgumentException("Room not found: " + re.getId()));
            existing.setRoomNumber(re.getRoomNumber());
            existing.setBaseRent(re.getBaseRent());
            existing.setAc(re.isAc());
            existing.setFloor(floor);
            existing.setBlock(block);
            if (existing.getSharingType() != re.getSharing()) {
                final List<Bed> beds = bedRepository.findByRoomId(existing.getId());
                final long occupied = beds.stream().filter(bed -> bed.getStatus() == BedStatus.OCCUPIED).count();
                if (occupied > 0) {
                    throw new IllegalStateException("Cannot change sharing type on occupied room: " + existing.getRoomNumber());
                }
                adjustRoomBeds(existing, re.getSharing());
                existing.setSharingType(re.getSharing());
            }
            room = roomRepository.save(existing);
        } else {
            room = roomRepository.save(Room.builder()
                    .floor(floor)
                    .block(block)
                    .roomNumber(re.getRoomNumber())
                    .sharingType(re.getSharing())
                    .baseRent(re.getBaseRent())
                    .isAc(re.isAc())
                    .build());
            String blockCode = null;
            if (block != null) {
                blockCode = block.getName();
                if (blockCode.contains(" ")) {
                    blockCode = blockCode.substring(blockCode.lastIndexOf(" ") + 1);
                }
            }
            createBeds(room, re.getSharing(), blockCode, null);
        }
        activeRoomIds.add(room.getId());
        return room;
    }

    /**
     * Resolves the room number for a standalone room — uses the explicit number from
     * {@link RoomConfig#getRoomNumbers()} if present, or auto-generates one.
     *
     * @param rc          the room configuration.
     * @param index       the 0-based index of this room within the configuration's count.
     * @param floorPrefix the floor prefix string (e.g., {@code "G"} for ground, {@code "1"} for first).
     * @param rIdx        the sequential room index on the floor (1-based), used for auto-generation.
     * @return the resolved room number string.
     */
    private String resolveRoomNumber(final RoomConfig rc, final int index,
                                     final String floorPrefix, final int rIdx) {
        if (hasExplicitRoomNumber(rc, index)) {
            return rc.getRoomNumbers().get(index).trim();
        }
        return floorPrefix + "-" + String.format("%02d", rIdx);
    }

    /**
     * Returns {@code true} if the {@link RoomConfig} supplies a non-blank explicit
     * room number for the given 0-based index position.
     *
     * @param rc    the room configuration.
     * @param index the 0-based index to check.
     * @return {@code true} if an explicit room number is available at {@code index}.
     */
    private boolean hasExplicitRoomNumber(final RoomConfig rc, final int index) {
        return rc.getRoomNumbers() != null
                && rc.getRoomNumbers().size() > index
                && rc.getRoomNumbers().get(index) != null
                && !rc.getRoomNumbers().get(index).isBlank();
    }
}
