package com.pgcrm.entity;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.SQLDelete;
import org.hibernate.annotations.SQLRestriction;

import java.time.LocalDate;
import java.time.LocalDateTime;

/**
 * Records a guest's daily meal opt-ins, add-on service usage, and dietary preference.
 *
 * <p>A {@code DailyLog} is created (or updated) once per guest per calendar day and
 * serves as the primary input to the monthly invoice generation pipeline. The
 * {@code InvoiceService} aggregates all {@code DailyLog} rows for a guest within a
 * billing period to compute the food and laundry line items on their invoice.</p>
 *
 * <p><strong>Soft Delete:</strong> Deletion is implemented as a logical flag via
 * Hibernate's {@link SQLDelete} and {@link SQLRestriction} annotations. The
 * {@code is_deleted} column is set to {@code true} on "delete", and the global
 * {@code SQLRestriction} filter ensures deleted rows are never returned by any
 * JPQL or criteria query without explicit override.</p>
 *
 * <p><strong>Meal Cutoff Model:</strong> In the default PG CRM arrears-billing model
 * ({@link BuildingConfig#isPreviousDay} = {@code true}), a log saved on Day N
 * reflects the meal choices for Day N-1. The {@code logDate} field always records
 * the <em>target</em> billing date, not the submission date.</p>
 *
 * <p><strong>Add-On Services:</strong> {@link #omeletteCount}, {@link #boiledEggCount},
 * and {@link #washingMachineCount} are non-negative integer counts of discrete
 * service units consumed during the day. These are multiplied by their respective
 * per-unit prices from {@link BuildingConfig} to produce billing amounts.</p>
 *
 * <p>A composite index on {@code (guest_id, log_date)} supports the most common
 * query pattern: fetching all logs for a specific guest within a date range.</p>
 *
 * @see Guest
 * @see BuildingConfig
 */
@Entity
@Table(
    name = "daily_logs",
    indexes = {
        @Index(name = "idx_daily_log_guest_date", columnList = "guest_id, log_date")
    }
)
@SQLDelete(sql = "UPDATE daily_logs SET is_deleted = true WHERE id=?")
@SQLRestriction("is_deleted = false")
@JsonIgnoreProperties(ignoreUnknown = true)
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class DailyLog {

    /** UUID primary key, generated by the database via {@link GenerationType#UUID}. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private String id;

    /**
     * Soft-delete flag. When {@code true}, this record is treated as logically deleted
     * and is excluded from all standard queries by the {@code @SQLRestriction} filter.
     * Defaults to {@code false}.
     */
    @Column(name = "is_deleted", nullable = false)
    @Builder.Default
    private boolean deleted = false;

    /**
     * The guest whose daily activity this record captures.
     * Loaded lazily; sensitive guest sub-associations are suppressed via
     * {@code JsonIgnoreProperties} to avoid over-fetching and serialisation cycles.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "guest_id", nullable = false)
    @JsonIgnoreProperties({"hibernateLazyInitializer", "handler", "bed", "user", "invoices"})
    private Guest guest;

    /**
     * The calendar date to which this log entry applies for billing purposes.
     * In the arrears model, this is the <em>previous</em> calendar day relative to
     * the date the record was submitted. Indexed alongside {@code guest_id}
     * for efficient date-range aggregation queries.
     */
    @Column(name = "log_date", nullable = false)
    private LocalDate logDate;

    // ── Meal Opt-In Flags ──────────────────────────────────────────────────────

    /**
     * Whether the guest opted in to breakfast on {@link #logDate}.
     * When the building charges per meal (food not included in rent),
     * a {@code true} value results in a breakfast charge on the monthly invoice.
     * Defaults to {@code false}.
     */
    @Column(name = "breakfast_opted")
    @Builder.Default
    private boolean breakfastOpted = false;

    /**
     * Whether the guest opted in to lunch on {@link #logDate}.
     * Defaults to {@code false}.
     */
    @Column(name = "lunch_opted")
    @Builder.Default
    private boolean lunchOpted = false;

    /**
     * Whether the guest opted in to dinner on {@link #logDate}.
     * Defaults to {@code false}.
     */
    @Column(name = "dinner_opted")
    @Builder.Default
    private boolean dinnerOpted = false;

    /**
     * The guest's dietary preference for {@link #logDate}: {@code true} = Vegetarian,
     * {@code false} = Non-Vegetarian. Communicated to the kitchen for meal preparation.
     * The {@link JsonProperty} annotation preserves the {@code "isVeg"} key name
     * during JSON serialisation regardless of getter naming conventions.
     * Defaults to {@code true} (vegetarian).
     */
    @Column(name = "is_veg")
    @Builder.Default
    @JsonProperty("isVeg")
    private boolean isVeg = true;

    // ── Add-On Service Counts ──────────────────────────────────────────────────

    /**
     * Number of omelette units consumed by the guest on {@link #logDate}.
     * Billed at {@link BuildingConfig#getOmelettePrice()} per unit.
     * Defaults to {@code 0}.
     */
    @Column(name = "omelette_count")
    @Builder.Default
    private int omeletteCount = 0;

    /**
     * Number of boiled egg units consumed by the guest on {@link #logDate}.
     * Billed at {@link BuildingConfig#getBoiledEggPrice()} per unit.
     * Defaults to {@code 0}.
     */
    @Column(name = "boiled_egg_count")
    @Builder.Default
    private int boiledEggCount = 0;

    // ── Laundry ────────────────────────────────────────────────────────────────

    /**
     * Number of washing machine cycles used by the guest on {@link #logDate}.
     * Billed at {@link BuildingConfig#getWashingMachinePrice()} per cycle.
     * Defaults to {@code 0}.
     */
    @Column(name = "washing_machine_count")
    @Builder.Default
    private int washingMachineCount = 0;

    // ── Audit Timestamps ───────────────────────────────────────────────────────

    /**
     * Server-side timestamp of when this log entry was first created.
     * Set automatically by {@link #onCreate()} and never modified subsequently.
     */
    @Column(name = "created_at")
    private LocalDateTime createdAt;

    /**
     * Server-side timestamp of the most recent modification to this log entry.
     * Updated automatically by both {@link #onCreate()} and {@link #onUpdate()}.
     */
    @Column(name = "updated_at")
    private LocalDateTime updatedAt;

    /**
     * JPA {@code @PrePersist} lifecycle callback that initialises both
     * {@link #createdAt} and {@link #updatedAt} to the current server time
     * immediately before the first database flush.
     */
    @PrePersist
    protected void onCreate() {
        createdAt = LocalDateTime.now();
        updatedAt = LocalDateTime.now();
    }

    /**
     * JPA {@code @PreUpdate} lifecycle callback that refreshes {@link #updatedAt}
     * to the current server time on every subsequent save operation.
     */
    @PreUpdate
    protected void onUpdate() {
        updatedAt = LocalDateTime.now();
    }

    @Transient
    @JsonProperty("breakfastDisabled")
    public boolean isBreakfastDisabled() {
        if (guest == null || guest.getCheckInDate() == null || logDate == null) return false;
        if (logDate.isBefore(guest.getCheckInDate())) return true;
        if (logDate.equals(guest.getCheckInDate())) {
            java.time.LocalDateTime checkInDateTime = guest.getCreatedAt() != null ? guest.getCreatedAt() : logDate.atStartOfDay();
            return checkInDateTime.toLocalTime().isAfter(java.time.LocalTime.of(10, 0));
        }
        return false;
    }

    @Transient
    @JsonProperty("lunchDisabled")
    public boolean isLunchDisabled() {
        if (guest == null || guest.getCheckInDate() == null || logDate == null) return false;
        if (logDate.isBefore(guest.getCheckInDate())) return true;
        if (logDate.equals(guest.getCheckInDate())) {
            java.time.LocalDateTime checkInDateTime = guest.getCreatedAt() != null ? guest.getCreatedAt() : logDate.atStartOfDay();
            return checkInDateTime.toLocalTime().isAfter(java.time.LocalTime.of(14, 0));
        }
        return false;
    }

    @Transient
    @JsonProperty("dinnerDisabled")
    public boolean isDinnerDisabled() {
        if (guest == null || guest.getCheckInDate() == null || logDate == null) return false;
        if (logDate.isBefore(guest.getCheckInDate())) return true;
        if (logDate.equals(guest.getCheckInDate())) {
            java.time.LocalDateTime checkInDateTime = guest.getCreatedAt() != null ? guest.getCreatedAt() : logDate.atStartOfDay();
            return checkInDateTime.toLocalTime().isAfter(java.time.LocalTime.of(21, 0));
        }
        return false;
    }
}
