package com.pgcrm.entity;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.pgcrm.entity.enums.InvoiceStatus;
import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.SQLDelete;
import org.hibernate.annotations.SQLRestriction;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

/**
 * Monthly invoice generated for a {@link Guest}, aggregating all billable charges
 * for a given calendar month and year.
 *
 * <p>An {@code Invoice} is the primary financial document in the PG CRM billing pipeline.
 * It is generated by the {@code InvoiceService} at the start of each month (arrears model),
 * covering the previous month's rent, food, electricity, and laundry charges. The total
 * is computed by summing the amounts across all associated {@link InvoiceLineItem} records.</p>
 *
 * <p><strong>Soft Delete:</strong> Invoices are never physically removed. The
 * {@code is_deleted} soft-delete flag and Hibernate's {@link SQLRestriction} filter
 * ensure deleted invoices are excluded from standard queries while preserving a
 * complete financial audit trail for compliance purposes.</p>
 *
 * <p><strong>Invoice Lifecycle and Status Transitions:</strong></p>
 * <ol>
 *   <li>{@link InvoiceStatus#GENERATED} — Invoice created; awaiting guest payment.</li>
 *   <li>{@link InvoiceStatus#PENDING_CASH_VERIFICATION} — Guest has initiated a cash
 *       handover; awaiting manager confirmation.</li>
 *   <li>{@link InvoiceStatus#PAID} — Payment verified (online via Razorpay, or cash
 *       confirmed by manager). {@link #paidAt} is stamped at this point.</li>
 *   <li>{@link InvoiceStatus#OVERDUE} — Due date has passed without payment;
 *       updated by the scheduled payment-reminder job.</li>
 * </ol>
 *
 * <p><strong>Razorpay Integration:</strong> Fields {@link #razorpayOrderId} and
 * {@link #razorpayPaymentId} are populated by the online payment flow. The
 * {@link #paymentMethod} field records the payment instrument used (e.g., {@code "UPI"},
 * {@code "CARD"}, {@code "NETBANKING"}) for reconciliation purposes.</p>
 *
 * <p>The {@link #lineItems} collection is fetched eagerly ({@link FetchType#EAGER})
 * because invoice detail views always require the full breakdown, and the collection
 * is typically small (≤ 10 items per invoice).</p>
 *
 * @see InvoiceLineItem
 * @see InvoiceStatus
 * @see Guest
 */
@Entity
@Table(name = "invoices")
@SQLDelete(sql = "UPDATE invoices SET is_deleted = true WHERE id=?")
@SQLRestriction("is_deleted = false")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Invoice {

    /** UUID primary key, generated by the database via {@link GenerationType#UUID}. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private String id;

    /**
     * Soft-delete flag. When {@code true}, this invoice is logically removed and excluded
     * from all standard JPA queries via the {@code @SQLRestriction} filter.
     * Physical data is retained to preserve billing history and audit compliance.
     * Defaults to {@code false}.
     */
    @Column(name = "is_deleted", nullable = false)
    @Builder.Default
    private boolean deleted = false;

    /**
     * The {@link Guest} to whom this invoice is addressed.
     * Loaded lazily; deep sub-associations on the guest are suppressed via
     * {@code JsonIgnoreProperties} to prevent serialisation cycles and over-fetching.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "guest_id", nullable = false)
    @JsonIgnoreProperties({"hibernateLazyInitializer", "handler", "bed", "user", "invoices"})
    private Guest guest;

    // ── Billing Period ─────────────────────────────────────────────────────────

    /**
     * The calendar month (1–12) this invoice covers.
     * Combined with {@link #year}, uniquely identifies the billing period per guest.
     * Example: {@code 5} = May.
     */
    @Column(name = "invoice_month", nullable = false)
    private int month;

    /**
     * The calendar year (e.g., {@code 2026}) this invoice covers.
     * Combined with {@link #month}, uniquely identifies the billing period per guest.
     */
    @Column(name = "invoice_year", nullable = false)
    private int year;

    // ── Financial ─────────────────────────────────────────────────────────────

    /**
     * The gross total amount due on this invoice, in Indian Rupees (₹).
     * Equals the sum of all {@link InvoiceLineItem#getAmount()} values in
     * the {@link #lineItems} collection. Defaults to {@code ₹0.00}.
     */
    @Column(name = "total_amount", precision = 10, scale = 2)
    @Builder.Default
    private BigDecimal totalAmount = BigDecimal.ZERO;

    // ── Status ────────────────────────────────────────────────────────────────

    /**
     * Current lifecycle status of this invoice.
     * Persisted as its {@code STRING} name for readability in reporting queries.
     * Defaults to {@link InvoiceStatus#GENERATED} at creation time.
     *
     * @see InvoiceStatus
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    @Builder.Default
    private InvoiceStatus status = InvoiceStatus.GENERATED;

    /**
     * The date by which payment must be received to avoid an overdue penalty.
     * Computed by the {@code InvoiceService} at generation time based on the
     * building's configured payment grace period.
     */
    @Column(name = "due_date")
    private LocalDate dueDate;

    // ── Audit Timestamps ───────────────────────────────────────────────────────

    /**
     * Server-side timestamp of when this invoice was generated.
     * Automatically set by {@link #onCreate()} and never modified thereafter.
     */
    @Column(name = "generated_at")
    private LocalDateTime generatedAt;

    /**
     * Timestamp of when the invoice was marked as paid.
     * Populated by the payment service upon successful Razorpay verification
     * or manager cash-confirmation. {@code null} if still unpaid.
     */
    @Column(name = "paid_at")
    private LocalDateTime paidAt;

    // ── Razorpay Online Payment ────────────────────────────────────────────────

    /**
     * The Razorpay Order ID created by the backend when the guest initiates
     * an online payment. Used to correlate Razorpay webhook callbacks to this invoice.
     * {@code null} for cash-paid invoices.
     */
    @Column(name = "razorpay_order_id")
    private String razorpayOrderId;

    /**
     * The Razorpay Payment ID returned after successful online payment capture.
     * Stored for reconciliation and refund processing.
     * {@code null} until payment is completed successfully.
     */
    @Column(name = "razorpay_payment_id")
    private String razorpayPaymentId;

    /**
     * The payment instrument used to settle this invoice.
     * Example values: {@code "UPI"}, {@code "CARD"}, {@code "NETBANKING"}, {@code "CASH"}.
     * Populated by the payment service at the time of confirmation.
     * {@code null} for unpaid invoices.
     */
    @Column(name = "payment_method")
    private String paymentMethod;

    // ── Reminders ─────────────────────────────────────────────────────────────

    /**
     * Timestamp when the automated 5-day overdue payment reminder was dispatched
     * to the guest via their configured notification channel.
     * A {@code null} value indicates the reminder has not yet been sent.
     * Set by the {@code PaymentReminderScheduler} once per invoice lifecycle.
     */
    @Column(name = "reminder_sent_at")
    private LocalDateTime reminderSentAt;

    // ── Line Items ─────────────────────────────────────────────────────────────

    /**
     * The itemised charge breakdown for this invoice.
     * Fetched eagerly because the line items are always required when an invoice
     * is loaded (detail view, PDF generation, payment initiation).
     * Cascade type {@code ALL} ensures line items are persisted and removed with
     * their parent invoice. Initialised to an empty {@link ArrayList} by default.
     *
     * @see InvoiceLineItem
     */
    @OneToMany(mappedBy = "invoice", cascade = CascadeType.ALL, fetch = FetchType.EAGER)
    @Builder.Default
    private List<InvoiceLineItem> lineItems = new ArrayList<>();

    /**
     * JPA {@code @PrePersist} lifecycle callback that stamps {@link #generatedAt}
     * with the current server time immediately before the first database flush.
     */
    @PrePersist
    protected void onCreate() {
        generatedAt = LocalDateTime.now();
    }
}
