package com.pgcrm.entity;

import com.pgcrm.entity.enums.MaintenancePriority;
import com.pgcrm.entity.enums.MaintenanceStatus;
import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDateTime;

/**
 * Represents a maintenance or repair request raised by a guest or manager.
 *
 * <p>A {@code MaintenanceTicket} tracks the lifecycle of a building maintenance issue —
 * from initial report through active resolution to closure. Guests can raise tickets
 * via the guest portal, while managers can view, prioritise, and resolve them from
 * the manager dashboard.</p>
 *
 * <p><strong>Ticket Lifecycle:</strong></p>
 * <ol>
 *   <li>{@link MaintenanceStatus#OPEN} — Ticket raised; awaiting manager acknowledgement.</li>
 *   <li>{@link MaintenanceStatus#IN_PROGRESS} — Manager has acknowledged and work has begun.</li>
 *   <li>{@link MaintenanceStatus#RESOLVED} — Issue fixed; {@link #resolvedAt} is stamped.</li>
 * </ol>
 *
 * <p><strong>Priority Levels:</strong> The {@link MaintenancePriority} field allows managers
 * to triage tickets by urgency ({@code LOW}, {@code MEDIUM}, {@code HIGH}), which drives
 * the sort order on the manager dashboard.</p>
 *
 * <p>The {@link #buildingId} field is stored as a plain {@code String} reference rather
 * than a JPA {@code @ManyToOne} association to avoid cross-aggregate coupling. The ticket
 * inherits the building context from its raising {@link Guest#getBed()} hierarchy.</p>
 *
 * @see MaintenanceStatus
 * @see MaintenancePriority
 * @see Guest
 */
@Entity
@Table(name = "maintenance_tickets")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class MaintenanceTicket {

    /** UUID primary key, generated by the database via {@link GenerationType#UUID}. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private String id;

    /**
     * The {@link Guest} who raised this maintenance ticket.
     * {@code null} for tickets created directly by a manager without a guest initiator.
     * Loaded lazily to avoid joining guest data on every ticket-list query.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "raised_by_guest_id")
    private Guest raisedByGuest;

    /**
     * UUID of the {@link Building} to which this maintenance ticket belongs.
     * Stored as a plain string reference to decouple the maintenance aggregate from
     * the building hierarchy and allow efficient filtering by building in manager queries.
     */
    @Column(name = "building_id")
    private String buildingId;

    /**
     * A concise, descriptive title of the maintenance issue.
     * Displayed in the ticket-list dashboard as the primary identifier.
     * Example: {@code "Leaking tap in Room 203 bathroom"}.
     */
    @Column(nullable = false)
    private String title;

    /**
     * The specific physical location within the building where the issue exists.
     * Example: {@code "Room 203, Block A, 2nd Floor"} or {@code "Common kitchen"}.
     * Helps maintenance staff locate the issue without additional communication.
     */
    @Column(nullable = false)
    private String location;

    /**
     * A detailed description of the maintenance problem, including any contextual
     * information that helps the resolution team diagnose the issue.
     * Maximum length: 1000 characters.
     */
    @Column(nullable = false, length = 1000)
    private String description;

    /**
     * Current resolution status of this ticket.
     * Persisted as its {@code STRING} name for readability in reporting.
     * Defaults to {@link MaintenanceStatus#OPEN} when a new ticket is raised.
     *
     * @see MaintenanceStatus
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    @Builder.Default
    private MaintenanceStatus status = MaintenanceStatus.OPEN;

    /**
     * Manager-assigned urgency level for this ticket, used to triage the resolution queue.
     * Persisted as its {@code STRING} name for readability.
     * Defaults to {@link MaintenancePriority#MEDIUM}.
     *
     * @see MaintenancePriority
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    @Builder.Default
    private MaintenancePriority priority = MaintenancePriority.MEDIUM;

    /**
     * Server-side timestamp of when this ticket was first created.
     * Automatically set by {@link #onCreate()} and never modified thereafter.
     */
    @Column(name = "created_at")
    private LocalDateTime createdAt;

    /**
     * Timestamp of when this ticket was marked as {@link MaintenanceStatus#RESOLVED}.
     * Populated by the manager when they close the ticket.
     * {@code null} for tickets that are still open or in progress.
     */
    @Column(name = "resolved_at")
    private LocalDateTime resolvedAt;

    /**
     * JPA {@code @PrePersist} lifecycle callback that stamps {@link #createdAt}
     * with the current server time immediately before the first database flush.
     */
    @PrePersist
    protected void onCreate() {
        createdAt = LocalDateTime.now();
    }
}
