package com.pgcrm.entity;

import jakarta.persistence.*;
import lombok.*;

import java.math.BigDecimal;
import java.time.LocalDate;

/**
 * Entity representing electricity or utility sub-meter readings for a room.
 */
@Entity
@Table(name = "meter_readings")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class MeterReading {

    /** UUID primary key, generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private String id;

    /** The room associated with this meter reading. */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "room_id", nullable = false)
    private Room room;

    /** Type of reading (e.g. MIGRATION_BASELINE). */
    @Column(name = "reading_type", nullable = false)
    private String type;

    /** Numeric reading value (e.g. kWh count). */
    @Column(name = "reading_value", nullable = false, precision = 10, scale = 2)
    private BigDecimal value;

    /** Date when reading was registered. */
    @Column(name = "reading_date", nullable = false)
    private LocalDate date;
}
