/**
 * JPA entity layer for the PG CRM application.
 *
 * <p>This package contains all JPA {@code @Entity} classes that map to the PostgreSQL
 * database schema, along with the {@code enums} sub-package holding all domain-specific
 * enumeration types used by these entities.</p>
 *
 * <p><strong>Spatial Hierarchy:</strong></p>
 * <pre>
 *   Building
 *     └─ Floor
 *          ├─ Block
 *          │    └─ Room
 *          │         └─ Bed
 *          └─ Room (standalone, no block)
 *               └─ Bed
 * </pre>
 *
 * <p><strong>Key Conventions:</strong></p>
 * <ul>
 *   <li>All primary keys are UUIDs generated by the database via
 *       {@link jakarta.persistence.GenerationType#UUID}.</li>
 *   <li>Soft-delete entities ({@link com.pgcrm.entity.Guest},
 *       {@link com.pgcrm.entity.Invoice}, {@link com.pgcrm.entity.DailyLog}) use
 *       Hibernate's {@code @SQLDelete} and {@code @SQLRestriction} annotations to
 *       implement logical deletion without physical row removal.</li>
 *   <li>All {@code @PrePersist} / {@code @PreUpdate} lifecycle callbacks use
 *       server-side {@link java.time.LocalDateTime#now()} for temporal consistency.</li>
 *   <li>Lazy loading ({@link jakarta.persistence.FetchType#LAZY}) is used by default
 *       on all associations to prevent N+1 query issues. {@code EAGER} is applied only
 *       where the collection is always required (e.g., {@code Invoice → lineItems}).</li>
 *   <li>{@code JsonIgnoreProperties} annotations on back-references suppress circular
 *       JSON serialisation without requiring {@code @JsonIgnore} on entire associations.</li>
 * </ul>
 *
 * <p>This application follows a <strong>single-tenant architecture</strong> — no
 * tenant discriminator column is required; data isolation is enforced at the
 * {@code branchId} (building scope) level in the service and security layers.</p>
 *
 * @see com.pgcrm.entity.Building
 * @see com.pgcrm.entity.Guest
 * @see com.pgcrm.entity.Invoice
 */
package com.pgcrm.entity;
