package com.pgcrm.entity;

import jakarta.persistence.*;
import lombok.*;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

/**
 * Represents a single room within a {@link Floor} or {@link Block} of a PG building.
 *
 * <p>A {@code Room} is the penultimate level in the PG CRM spatial hierarchy:
 * {@code Building → Floor → [Block →] Room → Bed}. Each room is subdivided into
 * one or more {@link Bed} units, the number of which is determined by the
 * {@link #sharingType} (e.g., {@code 2} for a double-occupancy room).</p>
 *
 * <p><strong>Block vs. Standalone:</strong> A room may be associated with a parent
 * {@link Block} (via {@link #block}) for organised floor layouts, or directly with
 * a {@link Floor} as a standalone room (when {@link #block} is {@code null}).
 * The {@link #floor} association is always required and serves as the primary
 * grouping reference for unblocked layouts.</p>
 *
 * <p><strong>Base Rent:</strong> The {@link #baseRent} field represents the per-bed
 * monthly rent for this room, configured by the Platform Admin. This value is used
 * by the {@code InvoiceService} as the {@link InvoiceLineItem} amount for the
 * {@code RENT} line type on each guest's monthly invoice.</p>
 *
 * <p>The {@code JsonIgnoreProperties} annotations on both {@link #block} and
 * {@link #floor} suppress upward collection traversal during JSON serialisation
 * to prevent infinite recursion.</p>
 *
 * @see Bed
 * @see Block
 * @see Floor
 */
@Entity
@Table(name = "rooms")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Room {

    /** UUID primary key, generated by the database via {@link GenerationType#UUID}. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private String id;

    /**
     * The parent {@link Block} containing this room.
     * {@code null} for standalone rooms attached directly to a floor with no block subdivision.
     * The {@code JsonIgnoreProperties} annotation prevents traversal back into the block's
     * room list during JSON serialisation.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "block_id")
    @com.fasterxml.jackson.annotation.JsonIgnoreProperties("rooms")
    private Block block;

    /**
     * The parent {@link Floor} on which this room is located.
     * Always required, even when a {@link #block} is also specified.
     * The {@code JsonIgnoreProperties} annotation suppresses upward collection
     * traversal to prevent infinite serialisation cycles.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "floor_id", nullable = false)
    @com.fasterxml.jackson.annotation.JsonIgnoreProperties({"rooms", "standaloneRooms"})
    private Floor floor;

    /**
     * Human-readable room identifier, unique within the building.
     * Convention: numeric strings such as {@code "101"}, {@code "202"}, or
     * alphanumeric labels like {@code "A1"}.
     * Displayed in the manager dashboard, bed-picker UI, and guest emails.
     */
    @Column(name = "room_number", nullable = false)
    private String roomNumber;

    /**
     * Maximum number of beds (occupants) this room can accommodate.
     * Example values: {@code 1} (single), {@code 2} (double), {@code 4} (quad).
     * Configured by the Platform Admin at building setup time.
     * The count must match the number of {@link Bed} records in {@link #beds}.
     */
    @Column(name = "sharing_type", nullable = false)
    private int sharingType;

    /**
     * Per-bed monthly base rent for this room, in Indian Rupees (₹).
     * Applied directly as the {@code RENT} line item on each occupant's monthly invoice.
     * Precision: 10 significant digits with 2 decimal places.
     */
    @Column(name = "base_rent", nullable = false, precision = 10, scale = 2)
    private BigDecimal baseRent;

    /**
     * Whether the room has Air Conditioning (AC).
     * Defaults to {@code false} (Non-AC).
     */
    @Column(name = "is_ac", nullable = false)
    @com.fasterxml.jackson.annotation.JsonProperty("isAc")
    @Builder.Default
    private boolean isAc = true;

    /**
     * All {@link Bed} records within this room.
     * Cascade type {@code ALL} ensures beds are persisted and removed with their parent room.
     * Initialised to an empty {@link ArrayList} to prevent {@code NullPointerException}
     * on new, unsaved room instances.
     */
    @OneToMany(mappedBy = "room", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    @Builder.Default
    private List<Bed> beds = new ArrayList<>();
}
