package com.pgcrm.dto;

import com.pgcrm.entity.Invoice;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.Collections;
import java.util.List;
import java.util.stream.Collectors;

/**
 * Outbound read model (response DTO) representing a guest's monthly invoice
 * and its itemised charge breakdown.
 *
 * <p>Returned by invoice-related endpoints for both the manager dashboard
 * ({@code GET /api/manager/invoices}, {@code GET /api/manager/invoices/{id}}) and
 * the guest portal ({@code GET /api/guest/invoices}). This DTO is a
 * <strong>flattened, serialisable projection</strong> of the {@link Invoice} aggregate,
 * avoiding direct entity exposure to the API layer.</p>
 *
 * <p><strong>Nested DTO:</strong> The inner class {@link InvoiceLineItemResponse}
 * represents a single charge line (rent, electricity, food, or laundry) within this
 * invoice. It is kept as a static inner class to keep the invoice and its line items
 * co-located and avoid cross-package coupling.</p>
 *
 * <p><strong>Mapping:</strong> The static factory method {@link #fromEntity(Invoice)}
 * performs a null-safe mapping of the {@link Invoice} entity and its
 * {@link com.pgcrm.entity.InvoiceLineItem} collection. The line items collection is
 * fetched with {@link jakarta.persistence.FetchType#EAGER} on the entity, so no
 * additional session context is required for the line-item traversal.</p>
 *
 * <p><strong>Payment Fields:</strong> {@link #razorpayOrderId} and
 * {@link #razorpayPaymentId} are populated only for invoices paid online via Razorpay.
 * They are {@code null} for cash-paid or unpaid invoices.</p>
 *
 * @see Invoice
 * @see com.pgcrm.entity.InvoiceLineItem
 * @see com.pgcrm.entity.enums.InvoiceStatus
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class InvoiceResponse {

    /** UUID of the {@link Invoice} entity. */
    private String id;

    /**
     * UUID of the {@link com.pgcrm.entity.Guest} to whom this invoice is addressed.
     * {@code null} if the guest association could not be resolved (data integrity issue).
     */
    private String guestId;

    /**
     * Full name of the guest, denormalised for display in invoice tables and PDF headers
     * without requiring a separate guest lookup on the client side.
     */
    private String guestName;

    /**
     * Calendar month (1–12) this invoice covers.
     * Example: {@code 5} = May.
     */
    private int month;

    /**
     * Calendar year (e.g., {@code 2026}) this invoice covers.
     * Combined with {@link #month}, uniquely identifies the billing period for a guest.
     */
    private int year;

    /**
     * Gross total amount due on this invoice, in Indian Rupees (₹).
     * Equals the sum of all {@link InvoiceLineItemResponse#getAmount()} values in
     * the {@link #lineItems} collection.
     */
    private BigDecimal totalAmount;

    /**
     * Current lifecycle status of this invoice, serialised as its enum name string.
     * Possible values: {@code "GENERATED"}, {@code "PAID"}, {@code "OVERDUE"},
     * {@code "PENDING_CASH_VERIFICATION"}.
     *
     * @see com.pgcrm.entity.enums.InvoiceStatus
     */
    private String status;

    /**
     * The date by which payment must be received to avoid an overdue classification.
     * Computed by the {@code InvoiceService} at generation time.
     */
    private LocalDate dueDate;

    /**
     * Server-side timestamp of when this invoice was generated by the billing pipeline.
     * Displayed in the invoice history list for audit and reference purposes.
     */
    private LocalDateTime generatedAt;

    /**
     * Timestamp of when the invoice was marked as paid.
     * {@code null} for invoices that are still unpaid, overdue, or pending verification.
     */
    private LocalDateTime paidAt;

    /**
     * Razorpay Order ID created when the guest initiates an online payment.
     * {@code null} for cash-paid or unpaid invoices.
     * Used by the frontend to resume a pending payment flow on page reload.
     */
    private String razorpayOrderId;

    /**
     * Razorpay Payment ID returned on successful online payment capture.
     * {@code null} until the payment is completed and verified via Razorpay webhook.
     * Stored for reconciliation and potential refund processing.
     */
    private String razorpayPaymentId;

    /**
     * Payment instrument used to settle this invoice.
     * Example values: {@code "UPI"}, {@code "CARD"}, {@code "NETBANKING"}, {@code "CASH"}.
     * {@code null} for unpaid invoices.
     */
    private String paymentMethod;

    /**
     * Itemised breakdown of all charges on this invoice.
     * Each entry corresponds to one {@link com.pgcrm.entity.InvoiceLineItem}.
     * Never {@code null} — defaults to an empty list for invoices with no line items.
     */
    private List<InvoiceLineItemResponse> lineItems;

    // ── Inner DTO ─────────────────────────────────────────────────────────────

    /**
     * Flattened projection of a single {@link com.pgcrm.entity.InvoiceLineItem},
     * representing one charge category on the parent invoice.
     *
     * <p>Kept as a static inner class to maintain co-location with its parent DTO
     * and avoid unnecessary package fragmentation for a tightly coupled projection.</p>
     *
     * @see com.pgcrm.entity.InvoiceLineItem
     * @see com.pgcrm.entity.enums.InvoiceLineType
     */
    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class InvoiceLineItemResponse {

        /** UUID of the {@link com.pgcrm.entity.InvoiceLineItem} entity. */
        private String id;

        /**
         * The charge category, serialised as its enum name string.
         * Possible values: {@code "RENT"}, {@code "EB"}, {@code "FOOD"}, {@code "LAUNDRY"}.
         *
         * @see com.pgcrm.entity.enums.InvoiceLineType
         */
        private String type;

        /**
         * Human-readable description of this charge line, shown in the invoice detail view
         * and PDF layout.
         * Example: {@code "Breakfast × 22 days @ ₹40"}, {@code "EB Share — Block B, May 2026"}.
         */
        private String description;

        /**
         * Monetary amount for this line item, in Indian Rupees (₹).
         * Precision: 10 significant digits with 2 decimal places.
         */
        private BigDecimal amount;
    }

    // ── Factory Method ────────────────────────────────────────────────────────

    /**
     * Null-safe static factory method that maps an {@link Invoice} entity
     * to a fully populated {@code InvoiceResponse} DTO.
     *
     * <p>The {@link Invoice#getLineItems()} collection is fetched with
     * {@link jakarta.persistence.FetchType#EAGER}, so no additional session
     * context is required. If the collection is {@code null} (edge case on
     * partially constructed entities), it safely defaults to an empty list.</p>
     *
     * <p>All enum fields ({@link com.pgcrm.entity.enums.InvoiceStatus},
     * {@link com.pgcrm.entity.enums.InvoiceLineType}) are serialised as their
     * string names to decouple the API contract from the enum structure.</p>
     *
     * @param invoice the {@link Invoice} entity to map; returns {@code null} if {@code null}.
     * @return a fully populated {@code InvoiceResponse}, or {@code null} if input is {@code null}.
     */
    public static InvoiceResponse fromEntity(final Invoice invoice) {
        if (invoice == null) {
            return null;
        }

        final List<InvoiceLineItemResponse> lines = invoice.getLineItems() == null
                ? Collections.emptyList()
                : invoice.getLineItems().stream()
                        .map(li -> InvoiceLineItemResponse.builder()
                                .id(li.getId())
                                .type(li.getType() != null ? li.getType().name() : null)
                                .description(li.getDescription())
                                .amount(li.getAmount())
                                .build())
                        .collect(Collectors.toList());

        return InvoiceResponse.builder()
                .id(invoice.getId())
                .guestId(invoice.getGuest() != null ? invoice.getGuest().getId() : null)
                .guestName(invoice.getGuest() != null ? invoice.getGuest().getFullName() : null)
                .month(invoice.getMonth())
                .year(invoice.getYear())
                .totalAmount(invoice.getTotalAmount())
                .status(invoice.getStatus() != null ? invoice.getStatus().name() : null)
                .dueDate(invoice.getDueDate())
                .generatedAt(invoice.getGeneratedAt())
                .paidAt(invoice.getPaidAt())
                .razorpayOrderId(invoice.getRazorpayOrderId())
                .razorpayPaymentId(invoice.getRazorpayPaymentId())
                .paymentMethod(invoice.getPaymentMethod())
                .lineItems(lines)
                .build();
    }
}
