# Server configuration
server.port=8090

# Database Configuration (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/controlplane_db
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA & Hibernate configuration
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Razorpay sandbox configurations
razorpay.key.id=rzp_test_mockKeyId12345
razorpay.key.secret=mockSecret
razorpay.webhook.secret=mockWebhookSecret
onboarding.setup-fee-inr=15000
