package com.pgcrm.entity;

import com.pgcrm.entity.enums.AuditAction;
import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDateTime;

/**
 * Persistent, immutable audit-trail record for the PG CRM application.
 *
 * <p>Every significant business event — such as guest check-ins, invoice generation,
 * payment collection, and system configuration changes — is captured as an
 * {@code AuditLog} entry by the {@code AuditService}. Records are written immediately
 * after the triggering transaction commits and are <strong>never modified</strong>
 * after initial persistence.</p>
 *
 * <p>The {@code timestamp} column is automatically populated by the {@link #onCreate()}
 * JPA lifecycle callback, ensuring server-side temporal consistency regardless of the
 * calling client's clock.</p>
 *
 * <p>Audit logs serve the following operational purposes:</p>
 * <ul>
 *   <li>Year-end audit reports and regulatory compliance reviews for the Building Owner.</li>
 *   <li>Real-time monitoring of critical operations (e.g., unauthorized access attempts).</li>
 *   <li>Forensic investigation of data anomalies and billing disputes.</li>
 * </ul>
 *
 * <p>Database indexes on the {@code timestamp} and {@code action} columns optimise the
 * date-range and action-type queries commonly executed by the audit dashboard endpoint.</p>
 *
 * @see AuditAction
 */
@Entity
@Table(
    name = "audit_logs",
    indexes = {
        @Index(name = "idx_audit_time",   columnList = "timestamp"),
        @Index(name = "idx_audit_action", columnList = "action")
    }
)
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class AuditLog {

    /** UUID primary key, generated by the database via {@link GenerationType#UUID}. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private String id;

    /**
     * The unique ID of the authenticated user who triggered the action.
     * A {@code null} value indicates the event was initiated by the system scheduler
     * (e.g., automated monthly invoice generation or payment-reminder dispatch).
     */
    @Column(name = "actor_id")
    private String actorId;

    /**
     * The application role of the actor at the time of the action
     * (e.g., {@code "PG_OWNER"}, {@code "PG_MANAGER"}, {@code "GUEST"}).
     * Stored as a plain {@code String} rather than an enum to preserve historical
     * accuracy if role names change in future application versions.
     */
    @Column(name = "actor_role", length = 30)
    private String actorRole;

    /**
     * Categorical classification of the audited business event.
     * Persisted as its {@code STRING} name for readability in raw SQL query results
     * and third-party reporting tools.
     *
     * @see AuditAction
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 50)
    private AuditAction action;

    /**
     * The domain entity type affected by the action.
     * Example values: {@code "Guest"}, {@code "Invoice"}, {@code "Bed"}, {@code "Building"}.
     */
    @Column(name = "entity_type", length = 50)
    private String entityType;

    /**
     * The UUID of the specific domain record that was affected.
     * Combined with {@link #entityType}, this pair uniquely identifies the target row
     * in the database for audit cross-referencing.
     */
    @Column(name = "entity_id")
    private String entityId;

    /**
     * A human-readable, plain-English summary of the event.
     * Example: {@code "Guest Rahul Kumar checked in to Bed A2, Room 101, Block B, Floor 2."}.
     */
    @Column(nullable = false, length = 500)
    private String description;

    /**
     * Optional JSON payload containing structured contextual data about the event —
     * for example, before/after field values, monetary amounts, or system parameters.
     * <p>Example: {@code {"oldStatus":"GENERATED","newStatus":"PAID","amount":5500.00}}</p>
     */
    @Column(name = "metadata", length = 2000)
    private String metadata;

    /**
     * The exact server-side instant at which this audit record was created.
     * Set automatically by {@link #onCreate()} and must never be mutated thereafter,
     * preserving the immutability guarantee of audit entries.
     */
    @Column(nullable = false)
    private LocalDateTime timestamp;

    /**
     * JPA {@code @PrePersist} lifecycle callback that stamps the {@link #timestamp}
     * with the current server time immediately before this entity is first flushed
     * to the database. This guarantees server-side temporal consistency, independent
     * of any client-supplied value.
     */
    @PrePersist
    protected void onCreate() {
        timestamp = LocalDateTime.now();
    }
}
