package com.pgcrm.entity;

import com.pgcrm.entity.enums.BedStatus;
import jakarta.persistence.*;
import lombok.*;

/**
 * Represents a single bookable bed unit within a {@link Room}.
 *
 * <p>A {@code Bed} is the finest-grained occupancy unit in the PG CRM hierarchy:
 * {@code Building → Floor → Block → Room → Bed}. Each bed carries a human-readable
 * label (e.g., {@code "A1"}, {@code "B2"}) that is used throughout the UI and
 * email notifications to identify the guest's allocated space.</p>
 *
 * <p>The {@link BedStatus} tracks the current occupancy state. Status transitions
 * are managed exclusively by the {@code BedService} to maintain data integrity —
 * a bed moves from {@code VACANT} to {@code OCCUPIED} at guest check-in, and back
 * to {@code VACANT} at checkout.</p>
 *
 * <p>The {@code JsonIgnoreProperties} annotation on the {@link #room} association
 * prevents infinite JSON serialisation loops when the parent {@link Room} is also
 * serialised with its bed list.</p>
 *
 * @see Room
 * @see BedStatus
 * @see Guest
 */
@Entity
@Table(name = "beds")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Bed {

    /** UUID primary key, generated by the database via {@link GenerationType#UUID}. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private String id;

    /**
     * The parent {@link Room} that contains this bed.
     * Loaded lazily to avoid unnecessary joins when only bed metadata is required.
     * The {@code JsonIgnoreProperties} prevents circular serialisation with
     * {@link Room#getBeds()}.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "room_id", nullable = false)
    @com.fasterxml.jackson.annotation.JsonIgnoreProperties("beds")
    private Room room;

    /**
     * Human-readable label that uniquely identifies this bed within its room.
     * Convention: single uppercase letter followed by a digit (e.g., {@code "A1"}, {@code "B2"}).
     * Displayed in UI tables, guest email notifications, and audit log descriptions.
     */
    @Column(name = "bed_label", nullable = false)
    private String bedLabel;

    /**
     * Current occupancy state of this bed.
     * Defaults to {@link BedStatus#VACANT} at creation time.
     * Transitions are: {@code VACANT → OCCUPIED} (check-in), {@code OCCUPIED → VACANT}
     * (checkout), and {@code VACANT → MAINTENANCE} (when the bed is taken offline
     * for repair by a manager).
     *
     * @see BedStatus
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    @Builder.Default
    private BedStatus status = BedStatus.VACANT;
}
