package com.pgcrm.entity;

import jakarta.persistence.*;
import lombok.*;

import java.util.ArrayList;
import java.util.List;

/**
 * Represents a named block (wing) of rooms on a given {@link Floor}.
 *
 * <p>A {@code Block} is an optional organisational subdivision of a floor, grouping
 * related rooms under a common label such as {@code "Block A"} or {@code "Girls' Wing"}.
 * The full spatial hierarchy is: {@code Building → Floor → Block → Room → Bed}.</p>
 *
 * <p>Not every floor requires blocks. Floors without blocks use the
 * {@link Floor#getStandaloneRooms()} collection instead. The distinction is preserved
 * to model real-world PG layouts where some floors have corridors segmented into
 * named wings while others have open room numbering.</p>
 *
 * <p>Cascade type {@link CascadeType#ALL} ensures that when a block is deleted, all
 * its child {@link Room} and grandchild {@link Bed} records are removed from the
 * database in a single operation.</p>
 *
 * <p>The {@code JsonIgnoreProperties} annotation on the {@link #floor} association
 * prevents infinite JSON serialisation cycles between {@code Floor ↔ Block ↔ Room}.</p>
 *
 * @see Floor
 * @see Room
 */
@Entity
@Table(name = "blocks")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Block {

    /** UUID primary key, generated by the database via {@link GenerationType#UUID}. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private String id;

    /**
     * The parent {@link Floor} to which this block belongs.
     * Loaded lazily; back-references to the floor's own collections are suppressed
     * via {@code JsonIgnoreProperties} to prevent serialisation cycles.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "floor_id", nullable = false)
    @com.fasterxml.jackson.annotation.JsonIgnoreProperties({"blocks", "standaloneRooms"})
    private Floor floor;

    /**
     * Human-readable name of the block, unique within its parent floor.
     * Convention: {@code "Block A"}, {@code "Block B"}, {@code "North Wing"}.
     * Displayed in the room-picker UI during guest check-in and bed-switch workflows.
     */
    @Column(nullable = false)
    private String name;

    /**
     * All {@link Room} records belonging to this block.
     * Cascade type {@code ALL} propagates persist, merge, and remove operations to
     * child rooms (and transitively to their beds).
     * Initialised to an empty {@link ArrayList} by default to prevent
     * {@code NullPointerException} on new, unsaved instances.
     */
    @OneToMany(mappedBy = "block", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    @Builder.Default
    private List<Room> rooms = new ArrayList<>();
}
