package com.pgcrm.entity;

import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

/**
 * Root aggregate representing a physical PG accommodation building.
 *
 * <p>A {@code Building} is the top-level entity in the PG CRM spatial hierarchy:
 * {@code Building → Floor → Block → Room → Bed}. Each building has its own
 * independent configuration (managed via {@link BuildingConfig}), its own set of
 * managers ({@code User.branchId}), and its own guest roster.</p>
 *
 * <p>This application follows a <strong>single-tenant architecture</strong> where a
 * single deployment may host multiple buildings, each operated as an independent PG.
 * The Platform Admin (PG Owner) manages all buildings, while PG Managers are scoped
 * to one or more specific buildings via their {@code branchId}.</p>
 *
 * <p>The {@code name} field carries a unique constraint to prevent accidental
 * duplicate building registrations. The {@link #createdAt} timestamp is automatically
 * set at persist time via the {@link #onCreate()} lifecycle callback.</p>
 *
 * @see BuildingConfig
 * @see Floor
 */
@Entity
@Table(name = "buildings")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Building {

    /** UUID primary key, generated by the database via {@link GenerationType#UUID}. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private String id;

    /**
     * The unique display name of this building, shown in the Owner dashboard,
     * manager dropdown selectors, and all guest-facing email communications.
     * A database-level unique constraint prevents duplicate building names.
     */
    @Column(nullable = false, unique = true)
    private String name;

    /**
     * Physical street address of the building.
     * Displayed in welcome emails and guest portal profile information.
     * May be {@code null} if the address has not yet been provided.
     */
    private String address;

    /**
     * Server-side timestamp of when this building record was first created.
     * Automatically populated by {@link #onCreate()} and never modified thereafter.
     */
    @Column(name = "created_at")
    private LocalDateTime createdAt;

    /**
     * All {@link Floor} records that belong to this building, ordered by floor number.
     * Cascade type {@code ALL} propagates lifecycle operations down through the full
     * spatial hierarchy: {@code Floor → Block → Room → Bed}.
     * Initialised to an empty {@link ArrayList} to prevent {@code NullPointerException}
     * on new, unsaved instances.
     */
    @OneToMany(mappedBy = "building", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    @Builder.Default
    private List<Floor> floors = new ArrayList<>();

    /**
     * The one-to-one operational configuration record for this building.
     * Holds all per-building settings: meal pricing, EB split method,
     * meal cutoff times, and allowed payment modes.
     * Uses {@code MapsId} semantics so the config's PK is the same UUID as this building.
     *
     * @see BuildingConfig
     */
    @OneToOne(mappedBy = "building", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    private BuildingConfig buildingConfig;

    /**
     * JPA {@code @PrePersist} lifecycle callback that stamps {@link #createdAt}
     * with the current server time immediately before the first database flush.
     * Ensures server-side temporal consistency, independent of client-supplied values.
     */
    @PrePersist
    protected void onCreate() {
        createdAt = LocalDateTime.now();
    }
}
