package com.pgcrm.entity;

import jakarta.persistence.*;
import lombok.*;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

/**
 * Represents a shared electricity bill recorded by a manager for a specific {@link Block}.
 *
 * <p>An {@code EbBill} captures the total electricity cost for a block over a defined
 * billing period, along with the split method used to divide the cost among resident guests.
 * The bill is then broken down into individual guest shares stored as
 * {@link EbBillGuest} records.</p>
 *
 * <p><strong>Split Methods:</strong> The algorithm for dividing the bill is determined
 * by the building's {@link BuildingConfig#getEbSplitMethod()} at the time of recording:</p>
 * <ul>
 *   <li>{@code EQUAL_SPLIT} — Total divided equally by the number of active guests.</li>
 *   <li>{@code PER_BED} — A fixed amount per bed, regardless of actual consumption.</li>
 *   <li>{@code METER_BASED} — Per-guest sub-meter readings stored in {@link EbBillGuest}.</li>
 *   <li>{@code MANAGER_MANUAL} — Manager enters each guest's amount individually.</li>
 * </ul>
 *
 * <p>The {@link #splitMethod} field stores the name of the algorithm applied at recording
 * time as a plain {@code String} to preserve the historical split choice even if the
 * building config changes in future periods.</p>
 *
 * <p>The individual guest-level shares (and, for meter-based splits, the meter readings)
 * are stored in the {@link #guestShares} collection via {@link EbBillGuest}.</p>
 *
 * @see EbBillGuest
 * @see BuildingConfig
 * @see com.pgcrm.entity.enums.EbSplitMethod
 */
@Entity
@Table(name = "eb_bills")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class EbBill {

    /** UUID primary key, generated by the database via {@link GenerationType#UUID}. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private String id;

    /**
     * The {@link Block} for which this electricity bill was recorded.
     * All beds within this block contribute to the shared bill total.
     * Loaded lazily to avoid unnecessary joins during list queries.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "block_id", nullable = false)
    private Block block;

    /**
     * The start date (inclusive) of the electricity billing period.
     * Typically corresponds to the meter-reading date of the previous cycle.
     */
    @Column(name = "billing_period_start", nullable = false)
    private LocalDate billingPeriodStart;

    /**
     * The end date (inclusive) of the electricity billing period.
     * Typically corresponds to the current meter-reading date.
     */
    @Column(name = "billing_period_end", nullable = false)
    private LocalDate billingPeriodEnd;

    /**
     * The total electricity bill amount for the block during this period, in Indian Rupees (₹).
     * This is the gross amount before any splitting calculation is applied.
     */
    @Column(name = "total_amount", nullable = false, precision = 10, scale = 2)
    private BigDecimal totalAmount;

    /**
     * The per-unit electricity rate applied to this bill, in Indian Rupees per kWh (₹/unit).
     * Only relevant when the split method is {@code METER_BASED}.
     * May be {@code null} for other split strategies where a rate per unit is not applicable.
     */
    @Column(name = "rate_per_unit", precision = 10, scale = 4)
    private BigDecimal ratePerUnit;

    /**
     * The name of the split algorithm applied when this bill was recorded.
     * Stored as a plain {@code String} (rather than the enum) to preserve the
     * historical split choice for auditing purposes, even if the building's
     * {@link BuildingConfig#getEbSplitMethod()} changes in future periods.
     * Example values: {@code "EQUAL_SPLIT"}, {@code "METER_BASED"}.
     */
    @Column(name = "split_method", length = 30)
    private String splitMethod;

    /**
     * Server-side timestamp of when this EB bill was first recorded by the manager.
     * Automatically set by {@link #onCreate()} and never modified thereafter.
     */
    @Column(name = "created_at")
    private LocalDateTime createdAt;

    /**
     * The collection of per-guest share records derived from this bill.
     * Each {@link EbBillGuest} entry holds the share amount for one resident guest
     * and, for meter-based splits, that guest's individual meter readings.
     * Cascade type {@code ALL} ensures shares are persisted and deleted with the parent bill.
     */
    @OneToMany(mappedBy = "ebBill", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    @Builder.Default
    private List<EbBillGuest> guestShares = new ArrayList<>();

    /**
     * JPA {@code @PrePersist} lifecycle callback that stamps {@link #createdAt}
     * with the current server time immediately before the first database flush.
     */
    @PrePersist
    protected void onCreate() {
        createdAt = LocalDateTime.now();
    }
}
