package com.pgcrm.entity;

import jakarta.persistence.*;
import lombok.*;

import java.math.BigDecimal;

/**
 * Join entity that records an individual guest's share of a shared electricity bill.
 *
 * <p>{@code EbBillGuest} is the line-item entity of the EB billing subsystem.
 * Each instance represents exactly one guest's portion of a single {@link EbBill},
 * capturing the computed share amount and — for meter-based splits — the
 * individual sub-meter readings used to derive that amount.</p>
 *
 * <p><strong>Split Method Context:</strong></p>
 * <ul>
 *   <li><strong>EQUAL_SPLIT / PER_BED:</strong> Only {@link #shareAmount} is meaningful;
 *       the meter reading fields are left {@code null}.</li>
 *   <li><strong>METER_BASED:</strong> All four fields are populated. The
 *       {@code EbService} computes
 *       {@code unitsConsumed = currentReading - previousReading}, then multiplies
 *       by the parent bill's {@link EbBill#getRatePerUnit()} to derive
 *       {@link #shareAmount}.</li>
 *   <li><strong>MANAGER_MANUAL:</strong> Only {@link #shareAmount} is populated,
 *       entered directly by the manager; reading fields are {@code null}.</li>
 * </ul>
 *
 * @see EbBill
 * @see Guest
 * @see com.pgcrm.entity.enums.EbSplitMethod
 */
@Entity
@Table(name = "eb_bill_guests")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class EbBillGuest {

    /** UUID primary key, generated by the database via {@link GenerationType#UUID}. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private String id;

    /**
     * The parent {@link EbBill} to which this guest-share record belongs.
     * Loaded lazily; the bill's block and period details are accessible via this association.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "eb_bill_id", nullable = false)
    private EbBill ebBill;

    /**
     * The {@link Guest} whose electricity share this record represents.
     * Loaded lazily; used by the invoice generation pipeline to attach EB charges
     * to the correct monthly invoice.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "guest_id", nullable = false)
    private Guest guest;

    /**
     * The computed electricity cost allocated to this guest for the billing period,
     * in Indian Rupees (₹). Always populated regardless of split method.
     * Precision of 10 digits with 2 decimal places matches Indian billing conventions.
     */
    @Column(name = "share_amount", nullable = false, precision = 10, scale = 2)
    private BigDecimal shareAmount;

    /**
     * The guest's sub-meter reading at the start of the billing period, in kWh.
     * Only relevant for the {@code METER_BASED} split method.
     * {@code null} for all other split strategies.
     */
    @Column(name = "previous_reading", precision = 10, scale = 2)
    private BigDecimal previousReading;

    /**
     * The guest's sub-meter reading at the end of the billing period, in kWh.
     * Only relevant for the {@code METER_BASED} split method.
     * {@code null} for all other split strategies.
     */
    @Column(name = "current_reading", precision = 10, scale = 2)
    private BigDecimal currentReading;

    /**
     * The total electricity units consumed by this guest during the billing period, in kWh.
     * Derived as: {@code unitsConsumed = currentReading - previousReading}.
     * Persisted for audit transparency; redundant but avoids re-computation on reads.
     * {@code null} for non-meter-based splits.
     */
    @Column(name = "units_consumed", precision = 10, scale = 2)
    private BigDecimal unitsConsumed;
}
