package com.pgcrm.entity;

import jakarta.persistence.*;
import lombok.*;

import java.util.ArrayList;
import java.util.List;

/**
 * Represents a single floor within a {@link Building}.
 *
 * <p>A {@code Floor} is the second level in the PG CRM spatial hierarchy:
 * {@code Building → Floor → Block → Room → Bed}. Each floor has a numeric ordinal
 * ({@link #floorNumber}) and an optional human-readable label ({@link #floorLabel})
 * displayed throughout the UI and guest communications.</p>
 *
 * <p><strong>Two Room Layouts:</strong> A floor can contain rooms in two ways:</p>
 * <ol>
 *   <li><strong>Block-organised rooms</strong> ({@link #blocks}): Rooms are grouped into
 *       named wings or blocks (e.g., "Block A", "Girls' Wing"). This is the default
 *       for floors with a large number of rooms requiring corridor-level organisation.</li>
 *   <li><strong>Standalone rooms</strong> ({@link #standaloneRooms}): Rooms attached
 *       directly to the floor without a parent block. Typical for ground floors or
 *       small layouts with only a handful of rooms.</li>
 * </ol>
 *
 * <p>The {@code @JsonIgnore} on {@link #building} prevents upward serialisation cycles
 * when a floor is included in API responses that already contain the parent building.</p>
 *
 * @see Building
 * @see Block
 * @see Room
 */
@Entity
@Table(name = "floors")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Floor {

    /** UUID primary key, generated by the database via {@link GenerationType#UUID}. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private String id;

    /**
     * The parent {@link Building} that contains this floor.
     * The {@code @JsonIgnore} annotation prevents infinite circular serialisation
     * when a full building tree is traversed from the floor upward.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "building_id", nullable = false)
    @com.fasterxml.jackson.annotation.JsonIgnore
    private Building building;

    /**
     * The zero-based or one-based integer ordinal of this floor within the building.
     * Convention: {@code 0} = Ground Floor, {@code 1} = First Floor, etc.
     * Used for sorting floor lists in the UI and bed-picker dropdowns.
     */
    @Column(name = "floor_number", nullable = false)
    private int floorNumber;

    /**
     * Human-readable display label for this floor, shown in the UI and guest communications.
     * Examples: {@code "Ground Floor"}, {@code "1st Floor"}, {@code "Terrace"}.
     * May be {@code null} if the Platform Admin has not yet assigned a custom label.
     */
    @Column(name = "floor_label")
    private String floorLabel;

    /**
     * All {@link Block} subdivisions belonging to this floor.
     * Cascade type {@code ALL} propagates lifecycle operations transitively to
     * child {@link Room} and grandchild {@link Bed} records.
     * Initialised to an empty {@link ArrayList} to prevent {@code NullPointerException}
     * on new, unsaved instances.
     */
    @OneToMany(mappedBy = "floor", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    @Builder.Default
    private List<Block> blocks = new ArrayList<>();

    /**
     * {@link Room} records attached directly to this floor, with no parent block.
     * Used for ground floors or layouts where room-level organisation without
     * block grouping is sufficient.
     * Initialised to an empty {@link ArrayList} to prevent {@code NullPointerException}.
     */
    @OneToMany(mappedBy = "floor", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    @Builder.Default
    private List<Room> standaloneRooms = new ArrayList<>();
}
