package com.pgcrm.entity;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.pgcrm.entity.enums.KycStatus;
import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.SQLDelete;
import org.hibernate.annotations.SQLRestriction;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;

/**
 * Core domain entity representing a PG accommodation guest.
 *
 * <p>A {@code Guest} is the central actor in the PG CRM system. Each guest record
 * corresponds to one {@link User} account (for portal login) and one assigned {@link Bed}
 * (their physical accommodation). The guest profile stores personal details,
 * occupancy dates, meal preferences, and the KYC verification state.</p>
 *
 * <p><strong>Soft Delete:</strong> Guest records are never physically deleted from the
 * database. Instead, the {@code is_deleted} flag is set to {@code true} via
 * Hibernate's {@link SQLDelete} annotation, and the {@link SQLRestriction} filter
 * excludes such records from all standard JPA queries. This preserves billing history,
 * audit logs, and invoice data for departed guests.</p>
 *
 * <p><strong>Guest Lifecycle:</strong></p>
 * <ol>
 *   <li><strong>Check-In:</strong> {@link #active} = {@code true}, {@link #checkInDate} set,
 *       {@link #bed} assigned, {@link User} account created.</li>
 *   <li><strong>Notice Issued:</strong> {@link #noticeDate} set; {@link #exitDate} computed
 *       as {@code noticeDate + noticePeriodDays} from the building config.</li>
 *   <li><strong>Checkout:</strong> {@link #active} = {@code false}, {@link #actualCheckOutDate}
 *       set, {@link Bed} status reverted to {@code VACANT}.</li>
 *   <li><strong>Re-Check-In:</strong> A new guest record is created; previous record remains
 *       soft-deleted for historical integrity.</li>
 * </ol>
 *
 * <p><strong>Meal Preferences:</strong> The {@code breakfastPreference},
 * {@code lunchPreference}, {@code dinnerPreference}, and {@code vegPreference} fields
 * store the guest's <em>default</em> daily preferences. These are used to auto-populate
 * each day's {@link DailyLog} if the guest has not explicitly opted in or out.
 * Day-specific overrides always take precedence.</p>
 *
 * @see User
 * @see Bed
 * @see DailyLog
 * @see Invoice
 * @see KycStatus
 */
@Entity
@Table(name = "guests")
@SQLDelete(sql = "UPDATE guests SET is_deleted = true WHERE id=?")
@SQLRestriction("is_deleted = false")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Guest {

    /** UUID primary key, generated by the database via {@link GenerationType#UUID}. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private String id;

    /**
     * Soft-delete flag. When {@code true}, this guest is logically removed from the
     * system and excluded from all standard JPA queries by the {@code @SQLRestriction}
     * filter. Physical data is retained for billing history and audit compliance.
     * Defaults to {@code false}.
     */
    @Column(name = "is_deleted", nullable = false)
    @Builder.Default
    private boolean deleted = false;

    /**
     * The associated {@link User} account that provides portal login credentials for
     * this guest. Loaded lazily; the password and sensitive auth fields are suppressed
     * via {@code JsonIgnoreProperties} in API responses.
     */
    @OneToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    @JsonIgnoreProperties({"hibernateLazyInitializer", "handler", "password"})
    private User user;

    /**
     * The {@link Bed} currently allocated to this guest.
     * {@code null} when the guest is in a pre-check-in state or has checked out.
     * The {@code room} sub-association on {@code Bed} is suppressed to prevent
     * unnecessary deep serialisation.
     */
    @OneToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "bed_id")
    @JsonIgnoreProperties({"hibernateLazyInitializer", "handler", "room"})
    private Bed bed;

    // ── Personal Details ───────────────────────────────────────────────────────

    /**
     * Full legal name of the guest, used in invoices, emails, and the manager dashboard.
     * Distinct from {@link User#getFullName()} to allow independent updates
     * (e.g., name correction after check-in without altering the login identity).
     */
    @Column(name = "full_name", nullable = false)
    private String fullName;

    /**
     * Primary email address of the guest, used for invoice delivery and OTP verification.
     * May differ from {@link User#getEmail()} if the guest has updated their contact email.
     */
    @Column(nullable = false)
    private String email;

    /** Primary contact phone number of the guest, stored in E.164 format. */
    @Column(nullable = false)
    private String phone;

    /**
     * WhatsApp-enabled phone number for push notification delivery.
     * May differ from {@link #phone} if the guest uses a separate WhatsApp number.
     * Used by the notification service when {@code channel = WHATSAPP}.
     */
    @Column(name = "whatsapp_number")
    private String whatsappNumber;

    /**
     * Vehicle registration number of the guest's 2-wheeler, if applicable.
     * Used for parking records and gate-entry logs.
     * Example: {@code "TN22AB1234"}.
     */
    @Column(name = "vehicle_registration", length = 20)
    private String vehicleRegistration;

    // ── KYC ───────────────────────────────────────────────────────────────────

    /**
     * Current KYC (Know Your Customer) verification status of this guest.
     * Updated by the manager after reviewing submitted identity documents.
     * Defaults to {@link KycStatus#PENDING} at check-in time.
     *
     * @see KycStatus
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "kyc_status")
    @Builder.Default
    private KycStatus kycStatus = KycStatus.PENDING;

    // ── Occupancy Dates ────────────────────────────────────────────────────────

    /** The date the guest officially checked in and their bed was assigned. */
    @Column(name = "check_in_date")
    private LocalDate checkInDate;

    /**
     * The originally planned check-out date communicated at the time of check-in.
     * Informational only; actual departure is tracked via {@link #actualCheckOutDate}.
     */
    @Column(name = "expected_check_out_date")
    private LocalDate expectedCheckOutDate;

    /**
     * The date on which the formal checkout notice was issued by the guest or manager.
     * Triggers computation of {@link #exitDate} based on the building's notice period.
     */
    @Column(name = "notice_date")
    private LocalDate noticeDate;

    /**
     * The computed exit date: {@code noticeDate + noticePeriodDays} (from building config).
     * Displayed in the manager dashboard to track upcoming vacancies.
     */
    @Column(name = "exit_date")
    private LocalDate exitDate;

    /** The date the guest physically vacated their bed and completed checkout. */
    @Column(name = "actual_check_out_date")
    private LocalDate actualCheckOutDate;

    // ── Financial ─────────────────────────────────────────────────────────────

    /**
     * The refundable security deposit collected from the guest at check-in, in Indian
     * Rupees (₹). Displayed in the guest profile and used for settlement calculations
     * at checkout. Defaults to {@code ₹0.00}.
     */
    @Column(name = "advance_deposit", precision = 10, scale = 2)
    @Builder.Default
    private BigDecimal advanceDeposit = BigDecimal.ZERO;

    // ── Status ────────────────────────────────────────────────────────────────

    /**
     * Whether this guest is currently active (checked in).
     * {@code false} indicates the guest has checked out; their record is retained
     * for billing history but excluded from most operational queries.
     * Defaults to {@code true}.
     */
    @Column(name = "is_active")
    @Builder.Default
    private boolean active = true;

    // ── Meal Preferences ──────────────────────────────────────────────────────

    /**
     * Default breakfast opt-in preference. When {@code true}, the daily log system
     * auto-opts the guest in to breakfast unless they explicitly cancel.
     * Defaults to {@code false}.
     */
    @Column(name = "breakfast_preference")
    @Builder.Default
    private boolean breakfastPreference = false;

    /**
     * Default lunch opt-in preference. When {@code true}, the daily log system
     * auto-opts the guest in to lunch unless they explicitly cancel.
     * Defaults to {@code false}.
     */
    @Column(name = "lunch_preference")
    @Builder.Default
    private boolean lunchPreference = false;

    /**
     * Default dinner opt-in preference. When {@code true}, the daily log system
     * auto-opts the guest in to dinner unless they explicitly cancel.
     * Defaults to {@code false}.
     */
    @Column(name = "dinner_preference")
    @Builder.Default
    private boolean dinnerPreference = false;

    /**
     * Default dietary preference for auto-populated daily logs.
     * {@code true} = Vegetarian, {@code false} = Non-Vegetarian.
     * Communicated to the kitchen for daily meal planning.
     * Defaults to {@code true} (vegetarian).
     */
    @Column(name = "is_veg_preference")
    @Builder.Default
    private boolean vegPreference = true;

    // ── Audit Timestamp ───────────────────────────────────────────────────────

    /**
     * Server-side timestamp of when this guest record was first created (check-in event).
     * Automatically set by {@link #onCreate()} and never modified thereafter.
     */
    @Column(name = "created_at")
    private LocalDateTime createdAt;

    /**
     * JPA {@code @PrePersist} lifecycle callback that stamps {@link #createdAt}
     * with the current server time immediately before the first database flush.
     */
    @PrePersist
    protected void onCreate() {
        createdAt = LocalDateTime.now();
    }
}
