package com.pgcrm.entity;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.pgcrm.entity.enums.InvoiceLineType;
import jakarta.persistence.*;
import lombok.*;

import java.math.BigDecimal;

/**
 * An itemised charge line within a guest's monthly {@link Invoice}.
 *
 * <p>Each {@code InvoiceLineItem} represents one distinct category of charge on an
 * invoice — such as rent, electricity, food, or laundry. The {@code InvoiceService}
 * creates one or more line items per invoice during the billing pipeline, depending
 * on which charges are applicable for the guest in that period.</p>
 *
 * <p><strong>Typical Line Item composition for a full month:</strong></p>
 * <ul>
 *   <li>{@link InvoiceLineType#RENT} — Fixed monthly base rent for the assigned bed.</li>
 *   <li>{@link InvoiceLineType#EB} — Guest's share of the block electricity bill.</li>
 *   <li>{@link InvoiceLineType#FOOD} — Aggregated meal charges from {@link DailyLog} records.</li>
 *   <li>{@link InvoiceLineType#LAUNDRY} — Aggregated washing machine usage charges.</li>
 * </ul>
 *
 * <p>The {@link #description} field provides a human-readable breakdown label
 * (e.g., {@code "Breakfast × 20 days"}) displayed in the guest portal and PDF invoices.</p>
 *
 * <p>The {@code JsonIgnoreProperties} annotation on the {@link #invoice} back-reference
 * prevents infinite serialisation loops when a full invoice tree is returned from the API.</p>
 *
 * @see Invoice
 * @see InvoiceLineType
 */
@Entity
@Table(name = "invoice_line_items")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class InvoiceLineItem {

    /** UUID primary key, generated by the database via {@link GenerationType#UUID}. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private String id;

    /**
     * The parent {@link Invoice} to which this line item belongs.
     * Loaded lazily; the {@code lineItems} and {@code guest} sub-associations on the
     * invoice are suppressed via {@code JsonIgnoreProperties} to prevent circular
     * serialisation when an invoice's line items are individually serialised.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "invoice_id", nullable = false)
    @JsonIgnoreProperties({"hibernateLazyInitializer", "handler", "lineItems", "guest"})
    private Invoice invoice;

    /**
     * The category of charge this line item represents.
     * Persisted as its {@code STRING} name for readability in reporting exports.
     *
     * @see InvoiceLineType
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private InvoiceLineType type;

    /**
     * Human-readable description of this line item, shown in the guest portal and PDF
     * invoice layout. Examples:
     * <ul>
     *   <li>{@code "Monthly Rent — Bed A1, Room 101"}</li>
     *   <li>{@code "Breakfast × 22 days @ ₹40"}</li>
     *   <li>{@code "EB Share — Block B, May 2026"}</li>
     *   <li>{@code "Washing Machine × 5 uses @ ₹20"}</li>
     * </ul>
     */
    private String description;

    /**
     * The monetary amount for this line item, in Indian Rupees (₹).
     * Precision: 10 significant digits with 2 decimal places, matching standard
     * Indian financial reporting conventions.
     */
    @Column(nullable = false, precision = 10, scale = 2)
    private BigDecimal amount;
}
