package com.pgcrm.entity;

import com.pgcrm.entity.enums.NotificationChannel;
import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDateTime;

/**
 * Records a notification dispatched to a guest or system user.
 *
 * <p>A {@code Notification} is created by the {@code NotificationService} whenever
 * the system needs to inform a user of an event — such as invoice generation, a
 * maintenance ticket status change, a payment confirmation, or a manager broadcast
 * message. Each notification targets a single recipient and a single delivery channel.</p>
 *
 * <p><strong>Recipient Model:</strong> A notification can be addressed to either
 * a {@link Guest} ({@link #guest}) or a system {@link User} ({@link #user}), but
 * not both simultaneously. The non-applicable field will be {@code null}:</p>
 * <ul>
 *   <li>Guest-targeted notifications (e.g., invoice alerts): {@link #guest} set,
 *       {@link #user} = {@code null}.</li>
 *   <li>Manager/Owner notifications (e.g., cash handover alerts): {@link #user} set,
 *       {@link #guest} = {@code null}.</li>
 * </ul>
 *
 * <p><strong>Delivery Channels:</strong> Determined by {@link NotificationChannel}.
 * {@code IN_APP} notifications appear in the guest/manager portal inbox and are
 * tracked by the {@link #read} flag. {@code WHATSAPP} notifications are dispatched
 * via the Twilio WhatsApp integration and tracked by {@link #deliveryStatus}.</p>
 *
 * <p>The {@link #sentAt} timestamp is automatically set by the {@link #onCreate()}
 * JPA lifecycle callback at persist time.</p>
 *
 * @see NotificationChannel
 * @see Guest
 * @see User
 */
@Entity
@Table(name = "notifications")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Notification {

    /** UUID primary key, generated by the database via {@link GenerationType#UUID}. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private String id;

    /**
     * The {@link Guest} who is the target of this notification.
     * Mutually exclusive with {@link #user} — exactly one should be non-{@code null}.
     * {@code null} for notifications targeting a manager or system user.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "guest_id")
    private Guest guest;

    /**
     * The {@link User} (manager or owner) who is the target of this notification.
     * Mutually exclusive with {@link #guest} — exactly one should be non-{@code null}.
     * {@code null} for notifications targeting a guest.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id")
    private User user;

    /**
     * The delivery channel through which this notification was dispatched.
     * {@link NotificationChannel#IN_APP} — stored in the database, visible in the portal inbox.
     * {@link NotificationChannel#WHATSAPP} — sent via Twilio WhatsApp API.
     *
     * @see NotificationChannel
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private NotificationChannel channel;

    /**
     * The full plain-text content of the notification message.
     * For {@code IN_APP} notifications: displayed verbatim in the portal inbox.
     * For {@code WHATSAPP} notifications: the message body sent to the WhatsApp API.
     * Maximum length: 2000 characters, accommodating structured templated messages.
     */
    @Column(nullable = false, length = 2000)
    private String message;

    /**
     * Server-side timestamp of when this notification record was created and the
     * message was dispatched. Automatically set by {@link #onCreate()} and never
     * modified thereafter.
     */
    @Column(name = "sent_at")
    private LocalDateTime sentAt;

    /**
     * Whether the recipient has read this notification in their portal inbox.
     * Applies only to {@link NotificationChannel#IN_APP} notifications.
     * Toggled to {@code true} when the guest or manager opens their inbox.
     * Defaults to {@code false}.
     */
    @Column(name = "is_read")
    @Builder.Default
    private boolean read = false;

    /**
     * Delivery status string for external channel notifications.
     * Example values: {@code "SENT"}, {@code "DELIVERED"}, {@code "FAILED"}.
     * Populated by Twilio webhook callbacks for WhatsApp messages.
     * {@code null} for {@code IN_APP} notifications, which have no external delivery state.
     */
    @Column(name = "delivery_status")
    private String deliveryStatus;

    /**
     * JPA {@code @PrePersist} lifecycle callback that stamps {@link #sentAt}
     * with the current server time immediately before the first database flush.
     */
    @PrePersist
    protected void onCreate() {
        sentAt = LocalDateTime.now();
    }
}
