package com.pgcrm.entity;

import jakarta.persistence.*;
import lombok.*;

import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * Per-building pricing override record for a named service or consumable.
 *
 * <p>{@code PricingConfig} stores manager-configurable unit prices that override the
 * application-level defaults defined in {@link BuildingConfig} for a specific building.
 * Each record is keyed by a {@code (buildingId, priceKey)} pair, enforced by a database
 * unique constraint, ensuring at most one active override per price type per building.</p>
 *
 * <p><strong>Supported Price Keys:</strong></p>
 * <ul>
 *   <li>{@code "breakfast"} — Per-meal breakfast price override (₹).</li>
 *   <li>{@code "lunch"} — Per-meal lunch price override (₹).</li>
 *   <li>{@code "dinner"} — Per-meal dinner price override (₹).</li>
 *   <li>{@code "omelette"} — Per-item omelette price override (₹).</li>
 *   <li>{@code "boiled_egg"} — Per-item boiled egg price override (₹).</li>
 *   <li>{@code "washing_machine"} — Per-use washing machine price override (₹).</li>
 * </ul>
 *
 * <p><strong>Resolution Precedence:</strong> The {@code PricingService} first checks
 * this table for a matching {@code (buildingId, priceKey)} row. If one exists, its
 * {@link #value} is used. If no override row is found, the system falls back to the
 * corresponding field in {@link BuildingConfig}.</p>
 *
 * <p>The {@link #updatedAt} timestamp and {@link #updatedBy} actor ID are refreshed on
 * every save via the {@link #onUpdate()} JPA lifecycle callback, providing a built-in
 * audit trail for pricing changes without requiring a separate event log entry.</p>
 *
 * @see BuildingConfig
 */
@Entity
@Table(
    name = "pricing_config",
    uniqueConstraints = @UniqueConstraint(columnNames = {"building_id", "price_key"})
)
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class PricingConfig {

    /** UUID primary key, generated by the database via {@link GenerationType#UUID}. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private String id;

    /**
     * UUID of the {@link Building} whose pricing this record overrides.
     * Stored as a plain string to decouple the pricing config from the building aggregate
     * and allow efficient lookup without a full entity join.
     */
    @Column(name = "building_id", nullable = false)
    private String buildingId;

    /**
     * The canonical name of the price being overridden.
     * Must match one of the supported keys: {@code "breakfast"}, {@code "lunch"},
     * {@code "dinner"}, {@code "omelette"}, {@code "boiled_egg"}, {@code "washing_machine"}.
     * Maximum length: 50 characters. Together with {@link #buildingId}, this forms
     * the composite unique key enforced by the database constraint.
     */
    @Column(name = "price_key", nullable = false, length = 50)
    private String priceKey;

    /**
     * The override price value for the named service, in Indian Rupees (₹).
     * Precision: 10 significant digits with 2 decimal places, consistent with
     * Indian financial reporting conventions.
     */
    @Column(name = "price_value", nullable = false, precision = 10, scale = 2)
    private BigDecimal value;

    /**
     * Server-side timestamp of when this pricing override was last saved.
     * Automatically refreshed on both initial persist and subsequent updates
     * by the {@link #onUpdate()} lifecycle callback.
     */
    @Column(name = "updated_at")
    private LocalDateTime updatedAt;

    /**
     * UUID of the {@link User} (manager or owner) who last modified this pricing record.
     * Set by the calling service layer before persisting, providing a lightweight
     * built-in audit trail for price changes.
     */
    @Column(name = "updated_by")
    private String updatedBy;

    /**
     * JPA lifecycle callback invoked both on initial persist ({@code @PrePersist})
     * and on every subsequent update ({@code @PreUpdate}). Stamps {@link #updatedAt}
     * with the current server time, ensuring the timestamp always reflects the
     * most recent modification.
     */
    @PrePersist
    @PreUpdate
    protected void onUpdate() {
        updatedAt = LocalDateTime.now();
    }
}
