package com.pgcrm.entity;

import com.pgcrm.entity.enums.Role;
import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDateTime;

/**
 * Authentication and identity record for every human actor in the PG CRM system.
 *
 * <p>A {@code User} provides the security principal for JWT-based authentication.
 * Every actor in the system — Platform Owner, PG Manager, and Guest — owns exactly
 * one {@code User} record. The {@link Role} enum determines which API endpoints and
 * dashboard views the user can access, enforced by Spring Security's method-level
 * security annotations.</p>
 *
 * <p><strong>Role-Specific Behaviour:</strong></p>
 * <ul>
 *   <li>{@link Role#PG_OWNER} — Full system access across all buildings. No branch restriction.</li>
 *   <li>{@link Role#PG_MANAGER} — Scoped to one or more buildings identified by
 *       the comma-separated {@link #branchId} field. The security filter layer validates
 *       every data-access request against this field to prevent cross-branch data leakage.</li>
 *   <li>{@link Role#GUEST} — Access limited to the guest portal; cannot view
 *       manager or owner dashboards.</li>
 * </ul>
 *
 * <p><strong>First-Login / Password-Change Flow:</strong> When a guest or manager account
 * is created by the owner, {@link #mustChangePassword} is set to {@code true}. The JWT
 * filter intercepts every request and redirects the user to the password-change page
 * until they set a permanent password. This prevents continued use of temporary credentials.</p>
 *
 * <p><strong>Account Lifecycle:</strong> Accounts are never physically deleted.
 * The {@link #active} flag deactivates access while preserving audit references.
 * Deactivated users cannot authenticate and all JWT tokens issued previously are
 * effectively invalidated on the next request cycle.</p>
 *
 * <p>A database index on the {@code email} column supports the most frequent
 * authentication lookup pattern: {@code findByEmail}.</p>
 *
 * @see Role
 * @see Guest
 */
@Entity
@Table(
    name = "users",
    indexes = {
        @Index(name = "idx_user_email", columnList = "email")
    }
)
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class User {

    /** UUID primary key, generated by the database via {@link GenerationType#UUID}. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private String id;

    /**
     * The user's unique email address, used as the login identifier across all roles.
     * A database unique constraint prevents duplicate accounts for the same email.
     * The email index optimises the frequent {@code findByEmail} authentication query.
     */
    @Column(nullable = false, unique = true)
    private String email;

    /**
     * BCrypt-hashed password credential.
     * <strong>Never</strong> returned in API responses; suppressed via
     * {@code @JsonIgnoreProperties} wherever a {@code User} reference is serialised.
     * Replaced on first login via the forced password-change flow.
     */
    @Column(nullable = false)
    private String password;

    /**
     * The application role assigned to this user, determining their access level.
     * Persisted as its {@code STRING} name for readability in database inspection.
     *
     * @see Role
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private Role role;

    /**
     * Comma-separated list of {@link com.pgcrm.entity.Building} UUIDs that this manager
     * is authorised to access.
     * <ul>
     *   <li>For {@link Role#PG_MANAGER}: contains one or more building UUIDs.</li>
     *   <li>For {@link Role#PG_OWNER} and {@link Role#GUEST}: typically {@code null}.</li>
     * </ul>
     * Validated on every manager API request by the branch-scope security filter to
     * prevent cross-building data access.
     */
    @Column(name = "branch_id")
    private String branchId;

    /**
     * Whether this user account is currently active and permitted to authenticate.
     * Deactivated accounts ({@code false}) are rejected at the JWT filter layer.
     * Defaults to {@code true} at account creation.
     */
    @Column(nullable = false, columnDefinition = "boolean default true")
    @Builder.Default
    private boolean active = true;

    /**
     * Whether this is the user's first login session.
     * Set to {@code false} after the user successfully completes their first authenticated
     * session. Used for first-login onboarding flows (e.g., profile completion prompts).
     * Defaults to {@code true}.
     */
    @Column(name = "first_login")
    @Builder.Default
    private boolean firstLogin = true;

    /**
     * When {@code true}, the JWT security filter forces this user to complete a
     * password-change before accessing any protected resource. Set to {@code true}
     * by the owner/manager when creating or resetting an account with a temporary
     * password. Reset to {@code false} upon successful password change.
     * Defaults to {@code false}.
     */
    @Column(name = "must_change_password")
    @Builder.Default
    private boolean mustChangePassword = false;

    /**
     * The user's display name shown in the portal header, dashboard greeting,
     * and email communications. For guest users, this is kept in sync with
     * {@link Guest#getFullName()} by the guest-management service.
     */
    @Column(name = "full_name")
    private String fullName;

    /** Contact phone number for the user account. Informational; not used for auth. */
    @Column(name = "phone")
    private String phone;

    /**
     * Server-side timestamp of when this user account was first created.
     * Automatically set by {@link #onCreate()} and never modified thereafter.
     */
    @Column(name = "created_at")
    private LocalDateTime createdAt;

    /**
     * Server-side timestamp of the most recent modification to this user record.
     * Automatically refreshed by both {@link #onCreate()} on initial persist and
     * {@link #onUpdate()} on every subsequent save.
     */
    @Column(name = "updated_at")
    private LocalDateTime updatedAt;

    /**
     * JPA {@code @PrePersist} lifecycle callback that initialises both
     * {@link #createdAt} and {@link #updatedAt} to the current server time
     * immediately before the first database flush.
     */
    @PrePersist
    protected void onCreate() {
        createdAt = LocalDateTime.now();
        updatedAt = LocalDateTime.now();
    }

    /**
     * JPA {@code @PreUpdate} lifecycle callback that refreshes {@link #updatedAt}
     * to the current server time on every subsequent save operation.
     */
    @PreUpdate
    protected void onUpdate() {
        updatedAt = LocalDateTime.now();
    }
}
